loopbackio/loopback-datasource-juggler

lib/dao.js
test/common_test.js

add a flag to callback of findOrCreate to indicate find or create

---

lib/connectors/memory.js
test/memory.test.js

undefined values should be moved to the end. The current sorting function returns 0, if a or b is undefined.

fix sorting of undefined values in memory connector

---

lib/model-builder.js

Fix id property returning undefined in certain situations.

Fix virtual id get function.

---

lib/model-definition.js
test/model-definition.test.js

fix id properties should sort by its index

---

lib/dao.js
test/manipulation.test.js

/to @bajtos or @ritch 
/cc @glesage
See https://github.com/strongloop/loopback/issues/1031

Make sure batch create calls back with correct data

---

lib/dao.js
lib/relation-definition.js
test/manipulation.test.js
test/relations.test.js

/to @bajtos or @ritch 
The PR is required to enable remoting for hasOne relations

Fix hasOne remoting

---

lib/connectors/memory.js
test/memory.test.js

/to @ritch  or @bajtos 
The PR fixes https://github.com/strongloop/loopback/issues/1058

Fix id type issue for update

---

lib/model-builder.js
test/loopback-dl.test.js

fix id property for composite ids

---

lib/dao.js
test/common.batch.js
test/manipulation.test.js

/to @bajtos 
Fixes strongloop/loopback-connector-mongodb#87

Remove undefined properties for create

---

lib/list.js
test/datatype.test.js

to / @bajtos,
Made following changes...
1) Set status code to 400, when client provides incorrect value.
2) Added test cases to verify the change.
Related: #709
Can you please review?

Return 400 when client provides an incorrect value

---

lib/model-builder.js
test/include.test.js
test/manipulation.test.js

/to @ritch 
See https://github.com/strongloop/loopback-connector-mongodb/issues/90

Enhance the coercion for boolean/date types

---

package.json
test/schema.test.js

it is not very important PR (so if you like how it is working now, feel free to close it), just wanted to point that perfomance degradation was fixed (i am ashamed that i have not noticed this before).

Remove workaround for perfomance degradation in should.js

---

lib/model-builder.js
test/loopback-dl.test.js

/to @ritch or @bajtos 
/cc @fabien 
See https://github.com/strongloop/loopback-datasource-juggler/issues/293

Make sure base properties/settings are merged into the submodel

---

lib/dao.js
test/crud-with-options.test.js
test/events.js

Fix `deleteById(id)` and other test failures

---

test/manipulation.test.js

/to @bajtos 
See https://github.com/strongloop/loopback-datasource-juggler/issues/457

Fix createdAt type so that it won't overflow SQL server int

---

test/manipulation.test.js
test/persistence-hooks.suite.js
test/relations.test.js

Tidy up tests so that they will work with RDBs

---

lib/dao.js
test/basic-querying.test.js
test/datatype.test.js
test/manipulation.test.js

/to @ritch or @bajtos 
/cc @fabien 
This PR prevents id values to be changed during prototype.attributes.

Make sure id properties cannot be changed

---

lib/model-builder.js

See https://github.com/strongloop/loopback-datasource-juggler/issues/512

Use the correct way to iterate over an array

---

lib/connectors/memory.js
test/basic-querying.test.js
test/manipulation.test.js

deleteAll returns number of deleted records

---

lib/jutil.js
test/mixins.test.js

fix #429 Multiple Models can't mixin same class.

fix #429 Multiple Models can't mixin same class

---

lib/connectors/memory.js
lib/connectors/transient.js
test/basic-querying.test.js
test/manipulation.test.js

The memory connector now includes the number of updated items in its callback
when updating records.
Connected to strongloop/loopback#1167

Memory connector returns updated records count

---

lib/connectors/transient.js

Fix the implementation to return an object as the result, that's the expected API since 04f35b3 (#502)
/cc @superkhau

Fix updateAll callback in "transient" connector

---

lib/scope.js
test/scope.test.js

@raymondfeng we might add this to the LB REST API later. What do you think?

Implement scope.findById

---

lib/scope.js
test/scope.test.js

Implement scope.findOne

---

test/manipulation.test.js

- Finalize delete/update tests to prepare for testing in all connectors
Connect to strongloop/loopback#1167
@bajtos @raymondfeng Merging this without code review as these are mainly cosmetic updates to ensure I have a solid baseline to run `manipulation.test.js` in each connector individually.

Clean up update/delete manipulation tests

---

test/manipulation.test.js

@bajtos @raymondfeng Merging without review as this is just a simple wording fix.

Fix wording in update test

---

test/manipulation.test.js

@bajtos @raymondfeng More minor wording updates, merging without review.

Clean up wording in update/delete tests

---

test/manipulation.test.js

Fixes for code review comments.
Connect to strongloop/loopback-datasource-juggler#530

Clean up delete and update tests

---

test/datatype.test.js

Check whether the connector enables strict mode and don't assert on dynamic properties in such case. This should fix test failures in SQL connectors like [loopback-connector-mssql](http://ci.strongloop.com/job/loopback-connector-mssql/81).
Connect to strongloop/loopback#1215
/to @raymondfeng please review.

Fix persistUndefinedAsNull tests w/ SQL connectors

---

lib/scope.js
test/scope.test.js

Another obvious addition to scopes. Currently remoting is yet to be implemented over at Loopback.

Implement scope.updateAll

---

lib/connectors/memory.js
lib/model-builder.js
lib/model.js
test/memory.test.js
test/model-definition.test.js

/to @bajtos or @ritch 
See https://github.com/strongloop/loopback/issues/517

Allow nesting properties to be queried for memory connector

---

lib/dao.js
test/crud-with-options.test.js

Extend findById to accept an optional filter object

---

lib/connectors/memory.js
lib/dao.js
test/datatype.test.js
test/memory.test.js

The PR allows the options argument to pass into connectors that choose to accept it. 
/to @bajtos or @ritch

Conditionally pass options to connector CRUD methods

---

docs.json
index.js
lib/connectors/memory.js
lib/dao.js
lib/include.js
lib/model.js
lib/observer.js
lib/relation-definition.js
lib/scope.js
lib/transaction.js
package.json

/to @ritch @bajtos 
This PR adds local transaction apis for relational DBs.
Connect to strongloop/loopback#109

Add transaction support

---

lib/dao.js
lib/model.js
lib/utils.js
test/util.test.js

/to @ritch 
/cc @Joesimonsen 
Connect to https://github.com/strongloop-internal/scrum-cs/issues/211

Enhance fieldsToArray to consider strict mode

---

lib/datasource.js
lib/observer.js
lib/transaction.js
test/async-observer.test.js
test/memory.test.js

This PR does a few things:
1. Enhance the observer mixin so that it allows around behavior
2. Enable connectors with observer apis
Connect to #464

Mix in observer apis to the connector

---

lib/include.js
test/include.test.js

/to @ritch 
Connect to https://github.com/strongloop/loopback/issues/1401

Fix for https://github.com/strongloop/loopback/issues/1401

---

lib/observer.js
test/async-observer.test.js

/to @ritch or @bajtos 
This PR enhances the observer APIs and add more tests.

Enhance the apis and add more tests

---

lib/relation-definition.js

addressing #603

---

lib/scope.js
test/relations.test.js

fix issue #587 
also add the proper unit test

fix issue #587

---

lib/model.js

fix a typo

---

support/describe-operation-hooks.js

/cc @crandmck You can find an example output in [slack archive](https://strongloop.slack.com/files/bajtos/F065RJ2JE/hooks.html). Perhaps we can include the table in [Operation Hooks](docs.strongloop.com/display/LB/Operation+hooks)? Ideally in a way that will make it easy to update the table content in the future, e.g. by copy-n-paste from the HTML file into raw confluence source markup.

Create a script to describe operation hooks

---

lib/relation-definition.js

See https://github.com/strongloop/loopback/issues/967

Allow 0 as the FK

---

lib/datasource.js
test/memory.test.js

Connect https://github.com/strongloop/loopback/issues/418
@bajtos,
Please review.

Promisify 'autoupdate'

---

test/persistence-hooks.suite.js

A followup for #599.
/cc @PradnyaBaviskar

test: fix persistence-hooks failures in MySQL

---

lib/include.js

Passing `options` to all find calls

Includes with transaction support

---

lib/dao.js
test/loopback-dl.test.js

/to @ritch 
This patch is result of https://groups.google.com/forum/#!topic/loopbackjs/zUQY1aQ5oGA

Fix coercion from ObjectID to String

---

lib/scope.js
test/scope.test.js

Don't cache static scope method results

---

lib/utils.js

Fix object merge

---

lib/dao.js
test/persistence-hooks.suite.js

Connect https://github.com/strongloop/loopback-datasource-juggler/issues/649
@bajtos, can you review?

Fix 'persist' hook for updateAttributes()

---

lib/connectors/memory.js
lib/dao.js
lib/utils.js
test/basic-querying.test.js
test/memory.test.js
test/util.test.js

Add support for RegExp operator

---

lib/dao.js
test/persistence-hooks.suite.js

Connect https://github.com/strongloop/loopback-datasource-juggler/issues/656#issuecomment-122942225
@raymondfeng, please review.
/cc @bajtos , @fabien

Async 'loaded' hook for find

---

lib/datasource.js
test/discovery.test.js

Connect https://github.com/strongloop/loopback/issues/418
Promisify following methods -
1. discoverModelDefinitions
2. discoverModelProperties
3. discoverPrimaryKeys
4. discoverForeignKeys
5. discoverExportedForeignKeys
6. discoverSchema
7. discoverSchemas
@bajtos - can you please review?

Promisify all 'discover' methods

---

lib/include.js
test/include.test.js

fixes issue 673: Include hasMany of relation does not return empty array

---

lib/geo.js

Fixed typo in nearby sort function & added the ability to specify units when filtering for nearby points.

Fixed typo & added the filter units

---

lib/relation-definition.js
lib/utils.js

Fix issue #695 by using string conversion before `indexOf` usage

Fix id comparison by using strings

---

lib/dao.js
lib/model-definition.js
test/basic-querying.test.js
test/model-definition.test.js

Relax id requirement for basic query operations

---

lib/dao.js
lib/model-definition.js
test/basic-querying.test.js
test/model-definition.test.js

Fix primary key checks

---

test/basic-querying.test.js
test/crud-with-options.test.js
test/datatype.test.js
test/hooks.test.js
test/manipulation.test.js
test/relations.test.js

Optimze automigrate() to cut the test time signicantly

---

lib/model.js
test/manipulation.test.js

Add support for using UUID V4 as defaultFn

---

lib/dao.js
test/relations.test.js

Fix filtering relations of a model with an order specified

---

lib/dao.js
lib/model-definition.js

fix a global leak and two typo

---

lib/include.js

fixes #753

---

Makefile
package.json

Cleaned up the Makefile and added a few helper scripts.

Update helper scripts

---

test/manipulation.test.js

Connect to https://github.com/strongloop/loopback-connector-mongodb/pull/204
See the connector PR for discussions.

Fix failing test for MongoDB connector

---

test/datatype.test.js

Hey Simon,
Please review
Thanks alot!

Redis test failiures

---

test/datatype.test.js

This reverts commit 62de2ed69eecc68fe0723efe6d34c81ab23ba98a.
This change fixes the tests for the other connectors that are failing due to missing EXPECTED value in tests. @Amir-61 will redo his changes after pulling in the latest updates for upgrading should to 8.0.2.

Revert "Correct syntax for should and more"

---

test/include.test.js

Add unit test to verify fix for #754

Add unit test to verify fix for #754

---

lib/dao.js

Re-factore `updateAttributes` to have code re-usability for newer methods

Refactor `updateAttributes`

---

lib/dao.js

Hi Miroslav,
I'm so sorry; [my earlier PR](https://github.com/strongloop/loopback-datasource-juggler/pull/826) was causing one of the test failures in loopback-connector-mongodb.

Fix conversion for `updateAttributes`

---

test/datasource.test.js

The test should have been added as part of #859 
/cc @ritch ehm, I forgot to add this file to git in my original pull request :(

Add forgotten unit test

---

lib/datasource.js

connect to https://github.com/strongloop/loopback-datasource-juggler/issues/872

Update error message for missing connector

---

package.json

@raymondfeng Please review.
Fix for test folder to be published.
I believe this needs to be backported to `2.x` as well?

Allow test folder to be published

---

package.json

Remove next tag for `2.x` branch

Remove next tag (2.x)

---

test/manipulation.test.js

Add automigrate to setup tables for replace test cases

Add automigrate to setup tables for replace test cases

---

lib/include.js
test/include.test.js

/to @bajtos 
See https://github.com/strongloop/loopback-datasource-juggler/issues/610

Partition by foreign key for pagination

---

lib/dao.js
test/persistence-hooks.suite.js

`find` should not trigger hooks if options.notify is false
@bajtos Please review :pray:

Fix notify for find method

---

3.0-RELEASE-NOTES.md

Add an entry for a breaking change made in 30283291 that was not described previously.
/to @Amir-61 please review

RELEASE-NOTES: describe 30283291

---

package.json

@bajtos Merging without review. Moving ESLint to devdep.

Set ESLint as devdep

---

test/relations.test.js

fix avoid duplicate record on scope with promise

---

test/persistence-hooks.suite.js

Add test's description

---

lib/dao.js

Return error if the connector returns an error for updateOrCreate
Connect to https://github.com/strongloop/loopback-datasource-juggler/pull/954

Retun err for UPSERT if the connector returns err

---

test/manipulation.test.js

* Add test for updateOrCreate when id is not autogenerated Id
Connect to https://github.com/strongloop/loopback-connector-db2/issues/38
@loay @superkhau @jannyHou Please review!
CC: @qpresley and @bajtos

Add test for updateOrCreate

---

lib/model.js

Remove unused variables in model.js
/to: @superkhau

Remove unused variables in model.js

---

test/manipulation.test.js

@superkhau  @loay 
I had forgot to backport https://github.com/strongloop/loopback-datasource-juggler/pull/989. This patch backports the patch to `2.x`
* Add test for updateOrCreate when id is not autogenerated Id
Connect to https://github.com/strongloop/loopback-datasource-juggler/pull/989
/to: @superkhau @0candy @loay
/cc: @bajtos

Add test for updateOrCreate[2.x]

---

lib/model.js

**Backporting**
Connect to https://github.com/strongloop/loopback-datasource-juggler/pull/1010

Remove unused variables in model.js [2.x]

---

test/manipulation.test.js

Backporting
Connect to https://github.com/strongloop/loopback-datasource-juggler/pull/1016
CC: @supasate

Fix test typo[2.x]

---

lib/dao.js
lib/list.js

Use `g.f(...)` instead of `g.f(utils.format(...))`
Comment from Tesuo is [here](https://github.com/strongloop/loopback-datasource-juggler/pull/1022/files#r73207761)
/to: @jannyHou

Use g.f instead of utils.format

---

index.js
lib/connectors/kv-memory.js
lib/datasource.js
lib/kvao/expire.js
lib/kvao/get.js
lib/kvao/index.js
lib/kvao/set.js
test/kv-memory.js
test/kvao.suite.js
test/kvao/_helpers.js
test/kvao/expire.suite.js
test/kvao/get-test.suite.js

KeyValue access object + memory connector

---

lib/connectors/kv-memory.js
test/kvao/expire.suite.js

@superkhau please review
cc @ritch

KeyValueAccessObject: return 404 when expiring unknown key

---

lib/connectors/kv-memory.js
test/kvao/expire.suite.js

KeyValueAccessObject: return 404 when expiring unknown key [2.x]

---

lib/connectors/kv-memory.js
lib/kvao/index.js
lib/kvao/ttl.js
test/kvao/ttl.suite.js

Backport of strongloop/loopback-datasource-juggler#1030
/cc @bajtos

Add TTL for KeyValue related features

---

.npmignore
lib/connectors/kv-memory.js
lib/kvao/index.js
lib/kvao/iterate-keys.js
lib/kvao/keys.js
package.json
test/kvao/_helpers.js
test/kvao/iterate-keys.suite.js
test/kvao/keys.suite.js

back-port of https://github.com/strongloop/loopback-datasource-juggler/pull/1049
connect to strongloop/loopback#2592

kvao: add iterateKeys() and keys() [2.x]

---

intl/en/messages.json
lib/connectors/kv-memory.js

Globalize KeyValue Memory connector

---

.eslintrc
lib/dao.js
lib/datasource.js
lib/model.js
lib/relation-definition.js

*Disable `strict` for a few files to disappear warnings
/to: @bajtos, @superkhau

Disable `strict` for a few files

---

test/manipulation.test.js
test/persistence-hooks.suite.js

* Fix failures of upsertWithWhere
Forwardport of #1052
/cc: @bajtos @superkhau

Fix failures of upsertWithWhere

---

test/kvao/ttl.suite.js

Refactor TTL test suite

---

test/include.test.js
test/manipulation.test.js

Fix BSON Object ID errors for CI

---

test/manipulation.test.js

connect to https://github.com/strongloop-internal/scrum-loopback/issues/1006
As agreed, in order to fix the CI issues with mssql, this test will be skipped temporarily till we fix the bug. 
PTAL @Amir-61 @0candy @superkhau

Skip test temporarily

---

test/manipulation.test.js

connect to https://github.com/strongloop/loopback-datasource-juggler/pull/1088

Backport Skip test temporarily

---

lib/kvao/expire.js
lib/kvao/get.js
lib/kvao/iterate-keys.js
lib/kvao/keys.js
lib/kvao/set.js
lib/kvao/ttl.js

@bajtos PTAL, docs matching LoopBack's KV model.
cc @crandmck 

Add docs for KVAO

---

lib/kvao/expire.js
lib/kvao/get.js
lib/kvao/iterate-keys.js
lib/kvao/keys.js
lib/kvao/set.js
lib/kvao/ttl.js

Backport: Add docs for KVAO

---

3.0-RELEASE-NOTES.md

Connect to: strongloop/loopback#2642
Add new entry in 3.x-release-notes to notify users the change of forceId.
According to issue https://github.com/strongloop/loopback/issues/2642#issuecomment-247348380
Related pr: https://github.com/strongloop/loopback-datasource-juggler/pull/982

Describe the change of forceId

---

lib/model.js
package.json
test/manipulation.test.js

Takeover: 1101

---

lib/dao.js
test/memory.test.js
test/persistence-hooks.suite.js

* Add 'isNewInstance' to loaded hook for updateAttributes
Backport of #1094 
Connect to strongloop-internal/scrum-loopback#1030
@superkhau Could you please approve this PR so I can land it?

Backport: Add 'isNewInstance' for updateAttributes

---

test/relations.test.js

connect to https://github.com/strongloop/loopback-connector-mysql/issues/196

Fix CI Failures in MySQL

---

lib/dao.js

* Fix JSDoc 
Connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1132
/cc: @superkhau

Fix JSDoc issue

---

lib/connectors/memory.js
lib/dao.js
test/basic-querying.test.js
test/init.js

Closes #633
Backport of #1091 
cc @bajtos @duffn

Backport: Add ilike and nilike operators

---

lib/model.js
package.json
test/manipulation.test.js

- Backport of strongloop/loopback-datasource-juggler#1107 (takeover of
strongloop/loopback-datasource-juggler#1101)
- Squashed relevant commits

Backport: Support {defaultFn: 'shortid'}

---

test/persistence-hooks.suite.js

* Add test for operation hook when near filter is used
Connect to https://github.com/strongloop/loopback-connector-mongodb/issues/285

Add test for operation hooks

---

lib/validations.js

Add doc of allowNull options property per #372.
Related to https://github.com/strongloop/loopback-datasource-juggler/commit/9a1ef0849575a124f963ceb2043916b0b89fbf40#commitcomment-19250964
/to: @superkhau @crandmck

Backport: Update validations.js

---

test/validations.test.js

Fix up #1109

---

test/loopback-dl.test.js

* Use imperative mood for tests in test/loopback-dl.test.js
Connect to #1150

Use imperative mood for tests

---

test/loopback-dl.test.js

* Apply style guide to test names in `test/loopback-dl.test.js`
* Backport of #1150
/to: @doublemarked  @superkhau PTAL; there were lots of merge conflicts while backporting #1150 
Thanks!

Apply style guide to test names

---

test/persistence-hooks.suite.js

Add more robust OH tests for find() method
Related to https://github.com/strongloop/loopback-datasource-juggler/pull/1149#issuecomment-256047743
/to: @superkhau @loay 
/cc: @bajtos

Add more robust OH tests for find method

---

test/persistence-hooks.suite.js

* Fix location for an instance in a test
/to: @superkhau

Fix a test

---

package.json

Add downstream ignore list config

---

test/manipulation.test.js
test/scope.test.js

Changes in `test/manipulation.test.js`, `test/scope.test.js`:
* `create()` does not return the result anymore in LB 3.0 so fixed-up tests accordingly
* use `if (err) return done(err);` instead of `should.not.exist(err);` for better error reorting
* remove un-used variables
/to: @superkhau
**Update 29/11/16**:
- Review done, just need to update PR and land.
**Update 30/11/16**:
- Changes made, @Amir-61 will check again and merge.

Tests cleanup

---

test/loopback-dl.test.js

Fix linter errors for CI

---

lib/relation-definition.js

Back-port #1197
Connect to strongloop/loopback#1495

Fix HasOne.update to propagate options arg [2.x]

---

package.json

Connect to https://github.com/strongloop/loopback/issues/2821

Update package.json for LB2-LTS release

---

test/.eslintrc
test/basic-querying.test.js
test/common_test.js
test/crud-with-options.test.js
test/datatype.test.js
test/default-scope.test.js
test/defaults.test.js
test/geo.test.js
test/hooks.test.js
test/include.test.js
test/introspection.test.js
test/loopback-dl.test.js
test/manipulation.test.js
test/memory.test.js
test/mixins.test.js
test/model-definition.test.js
test/optional-validation.test.js
test/persistence-hooks.suite.js
test/relations.test.js
test/schema.test.js
test/scope.test.js
test/transient.test.js
test/util.test.js
test/validations.test.js

Fix Block padding 
- Remove .eslintrc from loopback-datasource-juggler/test
- Run --fix
https://github.com/strongloop-internal/scrum-loopback/issues/1237

Fix block padding

---

lib/dao.js
lib/include.js
lib/relation-definition.js
lib/utils.js
package.json
test/common_test.js
test/geo.test.js
test/include.test.js
test/manipulation.test.js
test/operation-hooks.suite/embeds-many-create.suite.js
test/operation-hooks.suite/embeds-many-update-by-id.suite.js
test/operation-hooks.suite/embeds-one-create.suite.js
test/operation-hooks.suite/embeds-one-update.suite.js
test/relations.test.js
test/util.test.js

Also upgrade eslint itself to 3.x.

Upgrade eslint-config to 7.x

---

test/kvao/keys.suite.js

Connect to https://github.com/strongloop/loopback-datasource-juggler/pull/1218
cc @bajtos

Add missing return in KVAO keys test suite

---

test/kvao/delete-all.suite.js

Connect to https://github.com/strongloop/loopback-connector-kv-extreme-scale/pull/12
cc @bajtos

Add missing return for KVAO delete all

---

test/basic-querying.test.js

Add two basic tests for "inq" operator

---

lib/connectors/memory.js
lib/dao.js
test/manipulation.test.js

Fix Validation error
connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1235

Fix forceId validation error

---

lib/dao.js
test/allow-extended-operators.test.js

Refactor logic of options.allowExtendedOperators

---

lib/connectors/memory.js
test/memory.test.js

Add proper statusCode for http client error of Duplicate
connect to https://github.com/strongloop/loopback/issues/2512

Add proper statusCode for duplicate

---

test/basic-querying.test.js
test/init.js
test/memory.test.js

connect to strongloop/loopback#517
Support query nested properties

Support query nested properties

---

lib/validations.js
test/validations.test.js

- Add missing tests for `Validatable.validatesExclusionOf` method
- Fix proposal for the documentation
- #1121 

Add test coverage for `validatesExclusionOf`

---

lib/datasource.js

https://github.com/strongloop-internal/scrum-apex/issues/127

Add option for discoverModelDefinitions

---

test/validations.test.js

Add missing tests for Validatable.validatesInclusionOf method
- #1154 

Add test coverage for `validatesInclusionOf`

---

lib/model.js

Related PR: https://github.com/strongloop/loopback-datasource-juggler/pull/1272

Clean version of PR 1272

---

lib/dao.js
test/loopback-dl.test.js

Fixes inq where to allow regexp arrays
- None

Disallow regexp arrays for coerce

---

test/default-scope.test.js

Add collection name settings for arangodb database.
Required to pass common tests included in community connector
@ssh24 Backport of #1243

Override collection name for arangodb connector

---

lib/include.js
test/relations.test.js

This is a proposed fix to #1079. For more details of the issue please check out the issue.
Note I've targeted this fix to the `2.x-latest` branch. I'm not fully familiar with the v3 source code, but I believe this fix should be applied to the v3 branch as well. Happy to raise another PR for this if you agree.

Fix #1079 - Polymorphic hasMany inverse relation in include filter

---

lib/connectors/memory.js
lib/datasource.js
test/memory.test.js

Fix race condition for memory connector file read/write 
- None

Fix in-mem connector file operation racing condition

---

lib/relation-definition.js
test/relations.test.js

Custom Table Names on hasAndBelongsToMany Relationships
- #230 Custom Table Names on hasAndBelongsToMany Relationships

Custom Table Names on hasAndBelongsToMany Relationships

---

lib/dao.js
test/persistence-hooks.suite.js

create and patch now honor the option.notify flag. You may not always want to notify operational hooks that something has changed. 
Hopefully I did this pull-request correctly this time.

Added notify flag for create and upsert

---

lib/model-definition.js

Fix model definition column names method

---

lib/geo.js
test/basic-querying.test.js
test/geo.test.js

PR to revert back #1216. `CIS-Jenkins` was down when that PR was merged hence failures regarding other connector was not captured.

Revert ""Near" fix for where clauses"

---

package.json

https://github.com/strongloop-internal/scrum-apex/issues/170
- None

package: use loopback-connector@^4.0.0

---

test/basic-querying.test.js
test/datatype.test.js
test/helpers/uid-generator.js
test/manipulation.test.js
test/relations.test.js

Add support for Cassandra connector
- None

Add test support for Cassandra connector

---

test/relations.test.js

Fixup test support for Cassandra connector
- None

Fixup test support for Cassandra connector

---

test/relations.test.js

Remove debugger statement
- None

Remove debugger statement

---

lib/geo.js
test/basic-querying.test.js
test/geo.test.js

PR #1216 was reverted: CIS-Jenkins was down when that PR was merged hence failures regarding other connector were not captured.
This is the follow-up PR to address failures with connectors.
connected to https://github.com/strongloop-internal/scrum-apex/issues/168

handle deep geo-near queries

---

CONTRIBUTING.md

Add a description of how to run the unit tests to the contribution guidelines
- None

Add instructions for running the tests

---

package.json

Fix typo in description

---

lib/connectors/memory.js
lib/dao.js
test/manipulation.test.js

Fix forcedId bug validation error for updateOrCreate
connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1185

Fix forceId bug for updateOrCreate

---

lib/include.js
test/relations.test.js

Reverts strongloop/loopback-datasource-juggler#1080
It should not be checked into 2.x-latest, but 2.x

Revert "Fix #1079 - Polymorphic hasMany inverse relation in include filter"

---

lib/model.js

update api and js docs for modelbaseclass. 
connect to https://github.com/strongloop-internal/scrum-apex/issues/177

Update ModelBaseClass api docs

---

lib/dao.js
test/manipulation.test.js

Fix assertion statements and linting errors. 
to complement pr #https://github.com/strongloop/loopback-datasource-juggler/pull/1304

Fix error assertion

---

lib/include.js
lib/scope.js
lib/utils.js
package.json
test/include.test.js
test/relations.test.js

- https://github.com/strongloop/loopback-connector-cassandra/issues/8

Support include rework for C* connector

---

lib/model-builder.js

Quick nitpick fixes for the ModelBuilder API docs.
connected to https://github.com/strongloop-internal/scrum-apex/issues/179

ModelBuilder API Doc Touchup

---

lib/hooks.js

Add JSDoc for the deprecated trigger function in Hookable.
https://github.com/strongloop-internal/scrum-apex/issues/178

hooks: add JSDoc for .trigger

---

lib/include.js

Remove JSDoc from recursive calls
https://github.com/strongloop-internal/scrum-apex/issues/178

include: remove JSDoc refs to recursive calls

---

lib/datasource.js

Fixes https://github.com/strongloop-internal/scrum-loopback/issues/1538.

Remove spurious extra options arg

---

test/model-inheritance.test.js

Iterate through the actual model object to get the correct properties.
Fix of https://github.com/strongloop/loopback-datasource-juggler/pull/1384
connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1166

Apply iteration on the model object

---

lib/observer.js
lib/relations.js
lib/transaction.js
lib/validations.js

Docs checklist:
connect to https://github.com/strongloop-internal/scrum-apex/issues/180

Fix mixin and validatable docs

---

lib/include.js
lib/scope.js
lib/utils.js
package.json
test/relations.test.js

connect to strongloop-internal/scrum-apex#39
Backport of PR https://github.com/strongloop/loopback-datasource-juggler/pull/1153

Backport - Apply hasManyThrough filter on target model

---

test/basic-querying.test.js
test/datatype.test.js
test/include.test.js
test/manipulation.test.js
test/relations.test.js

connect to strongloop/loopback-connector-cloudant#33

Run juggler tests for Cloudant

---

README.md
lib/include.js
test/relations.test.js

~Backport~ Check in pr https://github.com/strongloop/loopback-datasource-juggler/pull/1080 into correct branch 
I checked it in to 2.x-latest by accident.
cc @alexpit

Fix polymorphic hasMany inverse relation

---

test/manipulation.test.js

Fixed short-circuiting of test cases preventing then from being run
standalone.

Fix tests failing when overridden for cloudant.

---

lib/dao.js
test/datatype.test.js
test/manipulation.test.js

Catch uncaught errors using cb wrapping. 
connect to https://github.com/strongloop/loopback/issues/1364
test cases here: https://github.com/strongloop/loopback/pull/3481

Catch errors using cb

---

test/persistence-hooks.suite.js

connect to https://github.com/strongloop/loopback-connector-mysql/issues/308
fixes https://github.com/strongloop/loopback-connector-mysql/issues/106

use connector flag throughout tests

---

lib/dao.js
test/crud-with-options.test.js

Fix #1434 2.55.1 Throws when using where query against "JSON Object or ANY" Type

---

lib/scope.js
test/relations.test.js

In scope.js, missing the option argument in find.relatedmodel
- #1388

Missing the option argument

---

test/relations.test.js

Sort the array so the ordering is the same
connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1446

Sort arrays before comparing

---

lib/dao.js
test/manipulation.test.js
test/validations.test.js

This PR is to honor backwards compatibility with validation on update.
connect to https://github.com/strongloop/loopback-datasource-juggler/pull/1445

Honor backwards compatibility with validate update

---

lib/dao.js
test/normalize-undefined.test.js

https://github.com/strongloop/loopback/issues/2364
- None

Fix undefined properties in where

---

package.json

Fix for advisory: https://snyk.io/vuln/npm:qs:20170213

package: use qs@6.5.0

---

intl/nl/messages.json

Updated the translated PII files from TVT first pass.
- none

Update translations from TVT

---

.travis.yml

Add node8 support for travis

---

lib/list.js
test/kv-memory.js
test/kvao.suite.js
test/list.test.js

Allow List to take items as instances of a class

---

lib/dao.js
lib/utils.js
test/model-definition.test.js
test/util.test.js

https://github.com/strongloop/loopback-datasource-juggler/issues/1651
- connect to #1653 #1651

Allow configuration of maxDepthOfQuery

---

lib/connectors/kv-memory.js
lib/connectors/memory.js
lib/date-string.js
lib/geo.js
lib/kvao/index.js
lib/relation-definition.js
lib/scope.js
lib/utils.js
package.json
test/async-observer.test.js
test/basic-querying.test.js
test/common_test.js
test/default-scope.test.js
test/helpers/context-test-helpers.js
test/helpers/hook-monitor.js
test/kvao/_helpers.js
test/kvao/expire.suite.js
test/kvao/get-set.suite.js
test/kvao/iterate-keys.suite.js
test/relations.test.js

- Upgrade bson to 4.x (latest)
- Update eslint-config-loopback to latest
- Update remaining dependencies
Skip update of shouldjs to avoid breaking tests in connectors.

Upgrade dependencies to their latest versions

---

.eslintrc
package.json

This is a follow-up for
- strongloop/loopback-datasource-juggler#1674 
- strongloop/loopback-datasource-juggler#1671
- https://github.com/strongloop/eslint-config-loopback/pull/34

Upgrade eslint-config-loopback to latest

---

lib/model-builder.js
lib/model-utils.js
lib/utils.js
test/datatype.test.js
test/model-builder.test.js

Enable to target ES6

---

package.json

fix: update lodash

---

.gitignore
.npmignore

Fix https://github.com/strongloop/loopback-datasource-juggler/issues/1708

fix: ignore .git folder

---

.gitignore
.npmignore

Fix https://github.com/strongloop/loopback-datasource-juggler/issues/1711

fix: ignore git file 4.x

---

.gitignore
.npmignore

Fix https://github.com/strongloop/loopback-datasource-juggler/issues/1711

fix: ignore git file 3.x

---

lib/include.js
test/include.test.js

Back-port https://github.com/strongloop/loopback-datasource-juggler/pull/1581 to 3.x. The changes were cherry-picked from 4.x by `git`, I did not have to make any adjustments.
/cc @spurreiter
See also #1580 

fix: normalize include with boolean or number [3.x]

---

lib/dao.js
lib/list.js
test/basic-querying.test.js
test/datatype.test.js
test/manipulation.test.js

Backport of #1702 to `3.x` branch.

Fix primitive datatypes coercion [3.x]

---

package.json

Related https://github.com/strongloop/loopback-datasource-juggler/pull/1710

Backport: Remove loopback-connector-kv-extreme-scale from downstream

---

package.json
test/datatype.test.js

Update `mocha` and `should` to latest

---

package.json

Update nyc to 14.0.0

---

lib/dao.js
lib/model-utils.js
test/manipulation.test.js
test/model-utils.test.js

https://github.com/strongloop/loopback-datasource-juggler/pull/1726 for master/`4.x` branch.

fix: allow coercion of nested properties

---

lib/date-string.js
test/date-string.test.js

Back-port https://github.com/strongloop/loopback-datasource-juggler/pull/1740 to 3.x
/cc @klarkc 
- https://github.com/strongloop/loopback-datasource-juggler/pull/1591

Fix DateString ctor to accept DateString instances [3.x]

---

lib/relation-definition.js
test/relations.test.js

Adds options to calls to attribute updates in EmbedsMany relations
- connect to #1724 

Fix for #1724 - Added options to attribute updates

---

types/datasource.d.ts

See https://github.com/strongloop/loopback-next/pull/3722

Fix typescript typing for DataSource.prototype.getModel()

---

lib/dao.js
test/manipulation.test.js

Backports #1790  to 3.X branch of juggler 

Return rejected promise on error [3.x]

---

lib/model.js
test/defaults.test.js

Backport of https://github.com/strongloop/loopback-datasource-juggler/pull/1813.

feat: added persistDefaultValues 3.x

---

package.json

See https://github.com/strongloop/loopback-next/pull/4729

deps: update uuid to v7

---

lib/datasource.js

connects to https://github.com/strongloop/loopback-next/issues/4763

mark idColumnName as deprecated

---

types/datasource.d.ts

this fix is needed in this [PR](https://github.com/strongloop/loopback-next/pull/5769)

Add definition attribute to datasource

---

package.json

Production dependencies:
- `loopback-connector` to  `^5.0.0` - see [release notes](https://github.com/strongloop/loopback-connector/blob/master/CHANGES.md#2020-08-28-version-500)
- `strong-globalize` to `^6.0.5` - see [release notes](https://github.com/strongloop/strong-globalize/blob/master/packages/runtime/CHANGELOG.md#600-2020-04-10)
- `uuid` to `^8.3.1` - see [release notes](https://github.com/uuidjs/uuid/blob/master/CHANGELOG.md#800-2020-04-29)
Dev dependencies:
- `eslint` to `^7.11.0`
- `mocha` to `^8.1.3`
- `typescript` to `^4.0.3`
Close https://github.com/strongloop/loopback-connector-postgresql/issues/463
/cc @billinghamj 
- Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html …

Update dependencies to latest 

---

README.md

see https://github.com/strongloop/loopback-next/issues/6709

chore: sync v4 EOL withh Node.js v14 EOL

---

README.md

see https://github.com/strongloop/loopback-next/issues/6957

chore: update 3.x LTS to End-of-Life

---

.github/codeql/codeql-config.yaml
.github/workflows/ci.yaml
.npmrc
.travis.yml
commitlint.config.js
package-lock.json
package.json

ci: update pipelines

---

lib/model.js
package-lock.json
package.json
test/manipulation.test.js

Replaces: https://github.com/loopbackio/loopback-datasource-juggler/pull/1893
Signed-off-by: Mario Estrada <marioestradarosa@yahoo.com>

deps: replace shortid with nanoid

---

lib/dao.js

closes https://github.com/loopbackio/loopback-datasource-juggler/issues/1971

fix: missing serialisation for `Connector.update`

---

.github/workflows/ci.yaml

chore: add Node.js 22 to CI

---

lib/datasource.js

feat: query to fetch unique columns

---

lib/dao.js
lib/model.js
lib/validations.js
test/kvao.suite.js

fix: Stop using `util._extend`
