- index.js
`__defineGetter__` is deprecated:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__
Replacing it with Object.defineProperty retains the same functionality but is ES5 standard:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Specifications.
This was causing a failure in IE.
> replace deprecated function __defineGetter__

- lib/connectors/memory.js
Remember, folks, `typeof null === 'object'`. Fixes #369.
> Fix for #369

- lib/model.js
- lib/validations.js
- test/manipulation.test.js
- test/relations.test.js
- test/validations.test.js
When building a list of errors for `ValidationError.message`, include
the values of invalid properties too.
In order to keep the message reasonably short, the values are truncated
at approx 32 characters.
See the unit-tests for examples of error messages.
Supersedes #368.
A part of strongloop/strong-arc#562
/to @raymondfeng @bitmage please review
/cc @fabien @ritch FYI
> Include property value in the error message

- lib/dao.js
- test/datatype.test.js
For queries, this is undesirable. It also affects loopback-connector-mongodb's ability to perform nested queries (it expects plain objects to work correctly, and to allow $elemMatch for example).
Related issue: https://github.com/strongloop/loopback/issues/953
> Don't coerce nested objects into Model instances

- lib/relation-definition.js
- test/relations.test.js
`BelongsTo.prototype.create` will call `modelInstance.save()` after `modelTo` has been created. If this behavior happens  in `ModelFrom.beforeCreate`, it will create a recursive loop.
But this fix might break something. See the test I altered.
Note: if `BelongsTo.prototype.create` is called in `ModelFrom.beforeUpdate()`, the model will be update twice (harmless I think)
> fix recursive calls if create belongsTo model in beforeCreate hook

- lib/model.js
Improve the detection to work in browser too. This fixes a regression
introduced in e4fc3878 (#389)
/cc @rmg @raymondfeng I'll merge without review to push the fix to npmjs ASAP.
> Fix detection of `util.inspect` version

- lib/model.js
- lib/relation-definition.js
- test/relations.test.js
PR for https://github.com/strongloop/loopback-datasource-juggler/issues/384
If ModelA belongsTo ModelB, this PR will include some properties of ModelB on instances of ModelA as embedded object. 
The effect is similar with using an `include` filter with `fields` option, but without extra db queries. Which is useful when denormalizing some properties.
> support embeds data for belongsTo relation

- lib/relation-definition.js
- test/relations.test.js
This is a tiny fix for relations with a function to transfer properties during creation. In order to preserve given target values specifically, provide the target to the properties function (if present, one can decide to override or keep as specified).
> Supply target to applyProperties function

- lib/validations.js
- test/validations.test.js
The current code `!(attr in this)` was not working (and I have written a unit test showing this). I have replaced it with a typeof undefined check. This then passes the unit test.
I have also written a couple of other unit tests to check other possible cases to ensure my change does not impact those.
> Fixed nullCheck in validations for undefined attributes

- lib/connectors/memory.js
- lib/dao.js
- lib/model-builder.js
- lib/model.js
- package.json
- test/async-observer.test.js
- test/hooks.test.js
- test/memory.test.js
- test/persistence-hooks.suite.js
Connect #367, see [my comment](https://github.com/strongloop/loopback-datasource-juggler/issues/367#issuecomment-70459067) there for description of this patch.
/to @raymondfeng @ritch please review
/cc @fabien FYI, feel free to chime in too
This patch introduces a new API for "intent-based" hooks. These hooks are not tied to a particular method (e.g. "find" or "update"). Instead, they are triggered from all methods that execute a particular "intent".
The consumer API is very simple, there is a new method `Model.observe(name, observer)`, where the observer is `function observer(context, callback)`.
Observers are inherited by child models and it is possible to register multiple observers for the same hook.
A list of hooks implemented by this PR follows below.
The `query` hook is triggered …
> Intent-based hooks for persistent models

- lib/dao.js
- test/manipulation.test.js
The commit 1fd6eff (intent-based hooks) introduced a subtle regression in `.save()` method where dynamic property setters were invoked twice.
This patch fixes the problem by moving pre-save data normalization into `before save` callback.
The second commit removes redundant `toObject` call which I discovered by reviewing the diff of 1fd6eff. Note that I was not able to write a unit-test that would fail due to this duplicate call.
Connect #367
> Fix regression in `.save()` from 1fd6eff

- lib/dao.js
- test/persistence-hooks.suite.js
Methods `DAO.deleteAll` and `DAO.prototype.delete` now invoke `before delete` hook too. The hook receives `ctx.where` describing models to be deleted.
Connect #367
/cc @ritch FYI
> Implement intent hook `before delete`

- lib/list.js
- lib/model.js
- test/model-definition.test.js
Protected properties allows you to define properties for an object which should not be included when nested. For instance if you have an Author object and a Book object. A book has a relation to with Author, and book is public API. Author will have personal information such as social security number etc, and they can now be "protected" such that anyone looking up the author of the book will not get those information back.
tldr: It's like the "hidden" feature, but it's only hidden when nested
> Add support for protected properties.

- lib/dao.js
- test/persistence-hooks.suite.js
The name "query" creates incorrect assumption that hook handlers may return the result of a query to bypass database access (see #417). That is far from true, since this hook is called also by methods like `deleteAll` or `updateAll` that don't perform any SELECT query.
Connect strongloop/loopback-datasource-juggler#367
/to @raymondfeng @ritch please review
/cc @crandmck FYI. I'll update the documentation myself when this is landed.
> Rename hook "query" to "access"

- package.json
- test/datatype.test.js
- test/defaults.test.js
- test/include.test.js
- test/loopback-dl.test.js
- test/relations.test.js
- test/schema.test.js
`should.eql` in `should@1.3` handles undefined and null properties differently than `should@1.2`. On the other hand, `should@1.2` does not have matchers that I need in the test suite for persistence hooks.
This patch upgrades should to the latest stable version.
/to @raymondfeng  please review
> Update to `should` to the latest version 4.6.3

- test/manipulation.test.js
Use `eql` instead of `equal` to support non-scalar id values used by MongoDB connector.
/cc @raymondfeng FYI
> Relax "id" checks in test/manipulation.test.js

- test/schema.test.js
/to @bajtos 
The PR fixes the performance issue by providing a custom message to `should.not.equal` calls. The `should` module always asserts the `equal` first, creates an `AssertionError`, and then tests the `not` condition. See See https://github.com/shouldjs/should.js/blob/master/lib/assertion.js#L47-L68. For complex objects, the [getMessage](https://github.com/shouldjs/should.js/blob/master/lib/assertion.js#L202-L208) is very expensive. It takes more than 4 seconds for a `DataSource` object that has references to many models.
I'll create an issue to should.js too.
> Fix the perf around should.not.equal for complex objects

- .editorconfig
- lib/datasource.js
- test/CustomTypeForeignKey.test.js
Initially this fix was proposed in strongloop/loopback-connector-postgresql#57 but @raymondfeng advised to move it into loopback-datasource-juggler.
So, here it is. :)
> Create model foreign key matching type of opposite part of relation (even if it has a custom field type)

- lib/dao.js
- test/crud-with-options.test.js
/to @bajtos @ritch 
This PR adds an optional `options` argument to all CRUD methods to make the APIs consistent. Some of them already start to take the `options` object after @bajtos implemented the intent-based hooks.
With the `options` argument, it's now possible to pass in more flags, such as `cascadeDelete`. 
Please note the connectors are yet to support the extra `options` argument.
> Add an optional `options` argument to all CRUD methods

- lib/dao.js
- test/memory.test.js
- test/persistence-hooks.suite.js
When using mongodb as database, I often use the native `findAndModify()` to perform a `find or create` (using `$setOnInsert` and `upsert` option). Since `findAndModify()` is an atomic operation, it won't cause conflict in some cases.
This PR tests that if the `connector` support `findOrCreate`, and if so then use it, otherwise `find()` or `create()`.
This PR use the new hook system introduced in https://github.com/strongloop/loopback-datasource-juggler/pull/403
> use optimized findOrCreate if possible

- lib/relation-definition.js
So hasOne#create could take advantage from optimized findOrCreate,
which can avoid multiple creation among concurrent requests.
> use findOrCreate in hasOne#create

- lib/relation-definition.js
- package.json
- test/relations.test.js
I created a quick test to describe the hasManyThrough issue I'm seeing.  I left in the console.log call so you can easily see the problematic object.  (pull in my PR and run npm test)
```json
{ "followerId": 2,
"date": "Wed Jan 14 2015 22:54:43 GMT-0800 (PST)",
"id": 1 }
```
`followerId` is being set but the `followeeId` attribute is not set; a critical piece when creating this object. This test demonstrates using the `add` function though I haven't testing with other relation functions like create.
> hasMany through doesn't set the through key value

- lib/model.js
- lib/utils.js
- package.json
- test/async-observer.test.js
- test/init.js
- Allow the observer functions passed to `ModelBaseClass.observe` to return a promise instead of calling the callback.
- Support both promise and callback styles in `ModelBaseClass.notifyObserversOf`.
Related: https://github.com/strongloop/strong-remoting/pull/179 and https://github.com/strongloop/loopback-datasource-juggler/pull/447
Connect strongloop/loopback#418
/to @raymondfeng Please review.
/cc @partap This patch provides the infrastructure needed for promise support, it's based on my comments in your PR. My plan is to land this PR first, so that you can use this infrastructure in your PR.
> Promises for operation hooks

- lib/model.js
- test/manipulation.test.js
to / @bajtos 
In reference to issue - https://github.com/strongloop/loopback/issues/292, added '$now' as a shortcut, to be used as default value for date property.
Can you please review?
> Add $now as shortcut default value for date property

- lib/model.js
- package.json
- test/manipulation.test.js
The property allows developers to specify that the default value should be retrieved via a named function.
Only two built-in functions are supported at the moment:
- `guid`, `uuid` - generate a new GUID/UUID
- `now` - use the current date and time
Support for custom (user-provided) functions is not implemented yet.
Connect #388, this PR supersedes #453.
/cc @ritch @fabien @kraman
> Add a new property option `defaultFn`

- lib/relation-definition.js
Remove all trailing whitespace to make @partap's work in #452 easier.
> There is a ton of trailing whitespace in relation-definition.js. I've been dancing around it with my commits... Could you take care of it in the master branch?
/cc @raymondfeng @ritch 
We should consider adding a `pretest` script running `jscs && jshint` as we do in loopback.
> relation-definition: remove trailing whitespace

- lib/dao.js
- test/basic-querying.test.js
Coerce ```data``` before updating models.
Relates to https://github.com/strongloop/loopback-connector-mysql/pull/74 .
> Enhance updateAll to coerce the data per property definitions

- lib/dao.js
- test/manipulation.test.js
Rebased and isolated DAO changes from https://github.com/strongloop/loopback-datasource-juggler/pull/447
Connects strongloop/loopback#418
> Promisify DAO

- Makefile
- lib/browser.depd.js
- lib/hooks.js
- lib/model-builder.js
- package.json
Deprecate the following [Model hooks](http://docs.strongloop.com/display/LB/Model+hooks):
- beforeValidate
- afterValidate
- beforeCreate
- afterCreate
- beforeSave
- afterSave
- beforeUpdate
- afterUpdate
- beforeDestroy
- afterDestroy
Deprecate the following Model events:
- changed
- deletedAll
- deleted
Closes strongloop/loopback#617.
/to @raymondfeng @ritch please review
> Deprecate model hooks and events

- lib/dao.js
- lib/scope.js
- test/relations.test.js
/to @ritch or @bajtos 
/cc @superkhau 
The PR ensures the scope on `include` is applied to the target model instead of the through model.
See https://github.com/strongloop/loopback/issues/1076
> Make sure inclusion filter is applied to the target model

- lib/dao.js
- test/persistence-hooks.suite.js
> Implement #484 : hookState

- lib/model-builder.js
- test/loopback-dl.test.js
/to @ritch @bajtos 
The PR allows sub-models to hide properties from its base. For example,
```json
"Customer": {
"base": "User",
"name": "String",
"username": null // or false
}
```
> Allow submodel to hide base properties

- lib/datasource.js
Use PK name of foreign class  to get columnMetadata.
Details: https://github.com/strongloop/loopback-connector-mysql/issues/84
> fix foreign key dataType bug

- lib/connectors/memory.js
- test/memory.test.js
Hello,
I happen to be using the memory datasource a lot but couldn't get "between" requests to work as documented here:
http://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-between
After trying every combination I could think of I finally figured that it could be a bug on loopback's side.
So here is my modest contribution.
Daniel
> Enable "between" filter for memory db connector

- lib/connectors/memory.js
- lib/dao.js
- test/manipulation.test.js
Modify the memory connector to reject requests to create a record with a duplicate id.
Add a unit-test to verify this behaviour across all connectors.
Connect to https://github.com/strongloop/loopback/issues/986
> Reject CREATE with a duplicate id

- lib/connectors/memory.js
- lib/dao.js
- test/persistence-hooks.suite.js
"before save" hooks provide "ctx.isNewInstance" whenever "ctx.instance" is set. Possible values:
- true for all CREATE operations
- false for all UPDATE operations
- undefined for "prototype.save"
"after save" hooks provide "ctx.isNewInstance" whenever "ctx.instance" is set. Possible values:
- true after all CREATE operations
- false after all UPDATE operations
- undefined after "updateOrCreate" and "prototype.save"
Note: both "updateOrCreate" and "prototype.updateAttributes" don't provide `ctx.instance` to "before save" hooks, therefore `ctx.isNewInstance` it not provided either.
Connect to strongloop/loopback#838
/cc @fabien @clarkorz 
Note that we will need to implement this feature in other connectors too, but unfortunately I don't have bandwidth for …
> Add ctx.isNewInstance for "save" hooks

- lib/dao.js
- test/manipulation.test.js
/to @bajtos or @ritch 
string/number and MongoDB ObjectID equality are now allowed.
> Enhance id comparision for updateAttributes

- lib/relation-definition.js
- test/relations.test.js
Before, singular relations (`hasOne`, `embedsOne`, `belongsTo`) were unable to extend the relationship accessor with custom methods - there was no scope to attach the methods to. 
This patch enables this in two ways:
1. you can specify `methods` as part of the relation options
2. you can use `defineMethod` as is the case with all other relation types
> Enable defineMethod for singular relations

- lib/relation-definition.js
Aparently only `__get__` was supported, while Loopback's `hasOneRemoting` already supported the other standard CRUD methods, leading to an exception in remoting's `SharedMethod.invoke` call.
There's a PR over at `loopback` with additional integration tests covering these methods.
> Enable more CRUD remoting methods for embedsOne

- lib/dao.js
- test/manipulation.test.js
ffcaa4e added a "data" argument to the callback function, which shadowed the original data with the data returned by a connector. Not all connectors are returning a data object though, in which casethe model instance ("this" object) is updated with wrong values.
This patch fixes the problem by renaming the second callback argument to "unusedData".
While I was working on this fix, I also improved the error messages reported by recently added unit-tests and replaced 
foo.count.should.equal(X)
Uncaught TypeError: Cannot read property 'should' of undefined
with more friendly
foo.should.have.property('count', X)`
Uncaught AssertionError: expected 0 to have property count
I am landing this without waiting for review to fix broken master ASAP. I'll address any comments in a follow-up pull …
> Fix regression in DAO.prototype.save

- lib/relation-definition.js
fix a problem that mentioned in strongloop/loopback-connector-mongodb#92
Notes:
1. The earlier commits add `.editorconfig`, I have separated the changes to a standalone commit beside the real patch 
2. I don't see the necessary to add new tests since they have already covered, and pass tests of strongloop/loopback-connector-mongodb#92
3. to @raymondfeng , although this PR fix the id problem, but for a `HasManyThrough#create`, it does **create** a **new** model every time, hence the through model will always been **created**, it would never been **found**. So the query is unnecessary if the connector doesn't support optimized `findOrCreate`. Is that ok?
> Always use findOrCreate when creating a through model

- lib/relation-definition.js
- lib/scope.js
- test/relations.test.js
Unless `persistent: true`, embedsMany needs a special implementation of `destroyAll`. It has all the same semantics as `scope` based `destroyAll`, but the usual caveats apply (due to the non-atomic operation of embedded relations).
> Properly support embedsMany destroyAll

- lib/jutil.js
- lib/relation-definition.js
- package.json
This commit is dropping lodash in favour of a hand-written implementation based on ES5 Array methods. As a result, the size of the (unminified) loopback browser bundle is decreased by approx 360KB (20%).
See https://github.com/strongloop/loopback/issues/989
/to @raymondfeng @fabien @ritch please review
> Remove all usages of lodash

- lib/dao.js
Rename the second callback argument to `info` to make its purpose more
clear. Fix jsdoc comments, note that these comments are NOT shown
on http://apidocs.strongloop.com/.
Connect to #1167.
/cc @superkhau
> Code cleanup in updateAll/deleteAll

- lib/dao.js
- lib/model-builder.js
- lib/model.js
- test/datatype.test.js
When the setting "persistUndefinedAsNull" is true, the model will use `null` instead of `undefined` in all property values:
- Known optional model properties are set to `null` when no value  was provided.
- When setting model properties, `undefined` is always converted  to `null`. This applies to both known (model-defined) properties  and additional (custom, dynamic) properties.
- The instance method `toObject()` converts `undefined` to `null` too. Because `toJSON()` calls `toObject()` under the hood, the change applies to `toJSON()` too.
Connect to strongloop/loopback#1215.
Once landed, the recommended model configuration will become
```json
{
"base": "PersistedModel",
"strict": true,
"persistUndefinedAsNull": true,
"trackChanges": true
}
```
/to @ritch @raymondfeng please review
/cc …
> Add model setting "persistUndefinedAsNull"

- lib/model.js
- test/async-observer.test.js
Users need to keep function references to be able to remove them from operation hooks.
> Add abilities to remove and clear observers - Operation Hooks.

- lib/dao.js
if left as-is, ids with value of zero were treated as non-existent. https://github.com/strongloop/loopback-datasource-juggler/issues/547
> check if id does not exist a bit more explicitly

- test/basic-querying.test.js
- test/manipulation.test.js
/to @bajtos 
For SQL server, if the PK is an identity, the id cannot be set for insert.
We also need to fix https://github.com/strongloop/loopback-datasource-juggler/blob/feature/fix-test-case/test/manipulation.test.js#L308 because not all connectors produce a message that contains `duplicate`.
> Fix the test cases so that they be run with the mssql connector

- lib/dao.js
- test/persistence-hooks.suite.js
It can be helpful to pass in `hookState`. Example scenario:
```
Model.observe('before save', function Foo(ctx, next) {
if (!ctx.hookState.value) return next(); // conditionally run hook
ctx.data.foo = ctx.hookState.value;
next();
}); 
Model.updateAll({ ... }, { ... }, { hookState: { value: 'bar' } }, function(err, result) {
...
});
```
/cc @raymondfeng @bajtos
> Allow passing in hookState from options

- lib/relation-definition.js
- test/relations.test.js
This fixes the situation where you may only have built an instance, and you're trying to persist an embedded model on it. Before, only `updateAttributes` would be performed, which then complained about a not existing model. 
(more specifically, in my case I would validate the existence of an embedsOne item, which would create a catch-22 type situation, when trying to save the parent model first).
> Save parent model of embedded relations

- lib/dao.js
- test/persistence-hooks.suite.js
Fix test for "after save" called on save/CREATE - make it correctly trigger the code path where the connector decides whether a new record is created or an existing one is updated.
Rename callback argument "result" to "info" to make it consistent with other places where we use "info" too.
Remove traling whitespace.
> Fix isNewInstance tests + code cleanup

- lib/model.js
- lib/validations.js
- test/loopback-dl.test.js
When a model is configured with `strict: 'validate'`, any dynamic properties not included in the schema trigger a validation error.
IMO, this is a much better solution that `strict: 'throw'`, as the latter may crash the whole application via an unhandled error.
/cc @ritch @fabien
> Add new strict mode "validate"

- lib/dao.js
- test/validations.test.js
Fix the implementation of updateOrCreate (a.k.a. upsert) to validate the model before calling the connector.
In order to preserve backwards compatibility, validation errors are only logged via console.warn by default.
The correct behaviour, where validation errors fail the updateOrCreate operation, can be enabled via new model setting "validateUpsert".
Connect to #262
/to @raymondfeng @ritch please review
My plan is to also modify `slc loopback:model` to enable this setting by default for all new models.
/cc @offlinehacker @fabien @clarkorz
> Validate model on updateOrCreate (upsert).

- lib/validations.js
- test/datatype.test.js
- test/validations.test.js
When a required number property is set to NaN, for example as a result of coersion (`Number([1,2,3])`), the "presence" validation now correctly reports an error.
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/243
> validations: treat `NaN` as a blank value

- lib/model-builder.js
- test/loopback-dl.test.js
> Allow leading slash for `path` in model settings

- lib/relation-definition.js
- test/relations.test.js
HasManyThrough is inconsistent because of arbitrary order of foreign keys returned by findBelongsTo. This fix sorts the result so that the first key is the one that is mapped to the base (modelFrom) model.
> Fix for https://github.com/strongloop/loopback-datasource-juggler/issues/571

- lib/scope.js
- lib/utils.js
- test/util.test.js
It should merge include filter in default scope (model definition) with the include filter in query.
In Model definition
```json
"scope":{
"include":"owner"
}
```
In query 
```js
Model.find({
include:{
posts:'comments'
}
})
```
After merging, the resulting query will be:
```js
{
include:{
owner:true
posts:'comments'
}
}
```
> Merge inclusion in default scope with inclusion in query.

- test/model-definition.test.js
Add a unit-test to capture the fact that a property type can be specified as `type: 'array'`.
Connect to strongloop/loopback#1327
/cc @fabien @PradnyaBaviskar 
/cc @ritch IIRC, you were the one who told me that "array" string is not a valid LDL property type. Well, it turns out it is a valid type :)
> Add unit-test for "array" type

- lib/dao.js
- test/validations.test.js
- `validateUpsert:true` reports validation errors back to the callback
- `validateUpsert:false` does not call `isValid()` at all
- any other value report validation errors via `console.warn`
Fix #570
This is a quick fix to support existing applications that are using MongoDB's `$setOnInsert` together with `updateOrCreate`, see #570 for more details. In the future, I'd like to implement `$setOnInsert` as a feature, see https://github.com/strongloop/loopback/issues/1360.
/cc @PuKoren Is this a good solution for your problem described in #570?
> dao: support validateUpsert:false

- lib/dao.js
- test/crud-with-options.test.js
We should probably also consider implementing the `validate` option for other methods like `create`, for consistency.
/cc @raymondfeng
> Pass-through options from save to create

- lib/include.js
- package.json
- test/include.test.js
The number of DB calls was to high especially in case of nested includes. New relic was showing ~100x db calls for includes. I had to fix it for our project and use our custom branch. But I have written few test cases and verified the tests. Please merge this if you think this looks good. 
Performance Improvement:
================
Tool: gobench (https://github.com/cmpxchg16/gobench)
Before Optimization:
================
Concurrent Clients which can be connected w/o error per single process (on my mac): ~300 but average response time was ~20 secs
Maximum Requests/sec per single process: ~47 req/s with 500 clients
Maximum Requests/sec with 3 cluster processes: ~78 req/s with 500 clients
After Optimization:
================
Note: Because of increase in processing, there's a negative impact …
> DB Call Optimization in relation includes - Fixes #408 & #166

- lib/include.js
- test/relations.test.js
This PR fixes a regression reported by https://github.com/strongloop/loopback-datasource-juggler/issues/594
> Make sure relation scope is applied during include

- lib/relation-definition.js
occure when try to delete object in has one relation, but object not created yet
> Fix ReferenceError: definition is not defined

- lib/validations.js
I had an issue in a test recently (using loopback-testing) where the test db was missing a column.
When running the test, the callback was never called and I get this very unhelpful message:
```
> NODE_ENV=test mocha --bail --compilers js:babel/register -R spec test/spec/*.js
Browse your REST API at http://0.0.0.0:8378/
LoopBack server listening @ http://0.0.0.0:8378/
accessTokens
when called by logged in user
GET /api/v1/position
1) "before each" hook
0 passing (2s)
1 failing
1) accessTokens when called by logged in user "before each" hook:
Error: timeout of 2000ms exceeded
at [object Object].<anonymous> (/Users/user/git/api/node_modules/mocha/lib/runnable.js:159:19)
at Timer.listOnTimeout (timers.js:110:15)
```
With this fix, I realize now that the column is missing:
```
accessTokens …
```
> Don't silently swallow db errors on validation.

- lib/dao.js
- test/persistence-hooks.suite.js
Connect to #559
Points to note -
- During `create` the updates applied through `persist` hook are reflected into the database, but the same updates are NOT reflected in the `instance` object obtained in callback of `create`.
- Secondly, `findOrCreate`, creates a new instance of the object every time. So, 
- Both `ctx.data.id` and `ctx.currentInstance.id` are set to new id. 
- And, `ctx.isNewInstance` is `true`
@bajtos, can you please review?
> Add new hook `persist`

- lib/datasource.js
- test/memory.test.js
Connect https://github.com/strongloop/loopback/issues/418
This PL, provides `promise` support to `automigrate` method of juggler's datasource.
@bajtos - can you review?
> Promisify 'automigrate'

- lib/include.js
- test/relations.test.js
polymorphic hasOne needs separate handling and hasMany->referencesMany has a unique case which is fixed for MongoDB as suggested by @fabien.
> Fix for issues #622 & #623

- lib/dao.js
- test/persistence-hooks.suite.js
Connect to #441
/to @raymondfeng, can you please review?
/cc @bajtos
> Add new hook 'loaded'

- lib/include.js
In order to fix @623 completely, the array of a referencesMany ids should be used for the order of returned items.
For this, `sortObjectsByIds` is appropriate. Somehow the Juggler tests did not uncover this pending issue, despite checking the order in reverse as well (see: https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/relations.test.js#L4895)
I only was able to find this after I finally updated my app (running with MongoDB) and running test there.
/cc @ningsuhen @bajtos
> Fix #623 - use actual id order

- lib/datasource.js
- lib/model-builder.js
- test/loopback-dl.test.js
/to @fabien 
/cc @ritch 
Sub models sometimes need to customize the properties from the base model.
This change allows each sub model has its own copy of the base property
definition to avoid potential conflicts across multiple sub models of the
same base.
> Make sure base property definitions are cloned

- lib/validations.js
- test/validations.test.js
Although most databases will enforce uniqueness of a primary key value, it should be possible to validate the `id` property explicitly. Once declared, you'll get a proper `ValidationError` and error details, instead of the error thrown by the connector/db itself.
/cc @raymondfeng
> Correctly handle validatesUniquenessOf(idName)

- lib/connectors/memory.js
- lib/dao.js
- lib/model.js
- test/defaults.test.js
- test/memory.test.js
clarkbw/loopback-ds-timestamp-mixin#11 was filed and it appears to be an issue with the upsert coming from juggler.
This PR creates a test that fails and I believe I’ve tracked down the area of the code that causes the issue, wrapped in `console.log` statements currently.
When you run the test it will print the following information:
```
not instance { id: 1000, name: 'updated name' }
inst { id: 1000,
name: 'updated name',
createdAt: Fri Jun 05 2015 09:59:03 GMT-0700 (PDT) }
1) should preserve default property values
```
As you can see in the debug output the `createdAt` field is being generated and then overwriting the existing `createdAt` field.  We need to prevent the default fields from being generated or passed to the update because default functions that are not idempotent will …
> default values are being overwritten in upsert

- lib/dao.js
- test/manipulation.test.js
This fixes https://github.com/strongloop/loopback/issues/742 in the following way:
- with strict: true, only known properties should be written to the dataSource
- from my findings, the data never made it to the dataSource, even before this fix (unlike what the issue above states)
- what **did** happen though, is that the in-memory representation was altered and returned, which was unaware of what was filtered or not (eg. actually written to the dataSource)
This distinction was clear from the test I added. Even before this fix, the last `should.not.exist(p.foo)` would pass correctly, however, the former `should.not.exist(p.foo)` call would not. With this fix, both pass.
> Filter attributes when strict: true

- lib/connectors/memory.js
- Check for undefined/null values when accessing `regexp` key
> Fix regexp error for the memory connector

- lib/connectors/memory.js
- lib/dao.js
- test/crud-with-options.test.js
- test/manipulation.test.js
Return `info.count` to the callback to indicate whether the model instance was deleted or not. When `options.strict` is true, return 404 error when the model instance was not found.
See #521 for the initial solution.
/to @raymondfeng @fabien please review
> Indicate result of destroyById/protototype.destroy

- lib/dao.js
- test/memory.test.js
Queries like `{where: {name: /John.*/i}}` should work. Notice there is no
`regexp` operator (ie. `{where: {name: {regexp: /John.*/i}}}`).
Connect to #681
> Do not coerce RegExp objects to strings

- lib/connectors/memory.js
- test/memory.test.js
Adds support for the ability to query embedsMany models from the parent.
Fix a memory connector bug that could occur when having an "or" or "and"
clause combined with another property. In that case, the and would revert
true for 'Paul McCartney'
```
{name:'John Lennon',and: [{role:'lead'}, {vip:true}]}}
```
> Support embedded query in memory connector. Fix memory connector bug

- lib/connectors/memory.js
- test/memory.test.js
Support mongo style matcher in where clause. 
embedsMany, referencesMany all have type array properties that can be filtered with when using loopback-mongo-connector. These don't have counterparts in relational dbs but precluding the use of the filters in the memory connectors complicates tests for mongo based apps.
Fixes the memory connector support mentionned in strongloop/loopback#953, strongloop/loopback#517.
Provides a baseline for the memory connector support of #625. At least for unit tests of a mongo based app.
Other issues related to this: #147
> Add support for matching array values à la mongo.

- lib/relation-definition.js
`findById` in `ReferencesMany` was comparing the `fkId` with itself. Hence `findById` method always returns the `modelTo` instance whether the `modelFrom` instance contains it or not.
Fixed the above issue by checking whether the `fkId` is present in `modelInstance[fk]`. 
cc: @fabien
> Fixed ReferencesMany .findById to check the given id in the modelInstance[fk]

- lib/datasource.js
- lib/relation-definition.js
- test/relations.test.js
Support for primaryKey for hasOne relation
```js
"lastData": {
"type": "hasOne",
"model": "LastData",
"foreignKey": "dataId",
"primaryKey": "dataId"
}
```
Were mentioned here: 
http://stackoverflow.com/questions/26802071/loopback-relationship-on-non-id-field
https://groups.google.com/forum/#!topic/loopbackjs/F1JcB4bTtxM
> primaryKey to hasOne relation

- lib/dao.js
This is a regression introduced in 2.39.0.
process.nextTick expects a function as its argument however in this case it was being given undefined with the result of a warning 'TypeError: callback is not a function'.
> findByIds would fail when an array of 0 length was passed as its first argument

- lib/dao.js
`allCb`, the helper function used in `find` wasn't calling a callback in certain cases.
That caused the server to hang in certain scenarios (eg. when filtering results in resources accessed by a hasManyThrough relationship).
This PR fixes bug https://github.com/strongloop/loopback/issues/1737
You can test the problem here: https://github.com/framp/loopback-bug-1737 (reverting the last commit which contains the solution).
The data provided to `allCb` was
```
[ { customerId: 1, itemId: 1, id: 1, item: { name: 'a', id: 1 } },
{ customerId: 1, itemId: 2, id: 2 } ]
```
The second item wasn't calling `callback`.
> Added missing callback when results are filtered

- lib/connectors/memory.js
- test/memory.test.js
Correction of a regression introduced by commit 632898b: when querying an empty array ([]) with a 'neq' filter, there were no matching.
For example:
a filter like this one:
’children': {
neq: 'barack'
}
On a set contain this object:
{
children: [],
id: 1
}
would not find any match.
Thanks to the correction I propose, the preceding situation leads to a match.
> Correction of a regression introduced by commit 632898b

- lib/include.js
- lib/include_utils.js
- test/include.test.js
- test/include_util.test.js
Hey guys, I'm not Loopback guru or even experienced user, but we were having some problems with performance of `hasMany` relation. 
It was affected cases when for ex. you have about 100 users (user hasMany permissions) and 100 permissions for them totally. As all join job done in app it was rather easy to trace whats going on. 
I introduced method `includeHasManySimple` which handles only simple cases of `hasMany` - without `subIncludes`. This is how it works: 
* building id -> obj1 map in object form to make by-id queries easy 
* collects ids to query from 2nd model
* builds and run query on 2nd model
* after that result of 2nd query collected to id -> [obj] map which make by-id queries easy and fast again
* for each object in 1st map cache filled and `processTargetObj` called 
This …
> With simpe and fast hasmany

- lib/observer.js
see http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it
> silence a warning that introduced in bluebird 3.0.x

- lib/datasource.js
If the PK has a definition like
```
"mysql": {
"dataType": "CHAR",
"dataLength":36,
"nullable":"N"
}
```
dataLength is ignored when the PK is used as a foreignKey in other models
> foreignKey dataLength fix

- lib/dao.js
I came across this bug when an update attribute call was violating a database restriction. In this case the api call returned 200 and didn't update the database.
Since I don't know what the Strongloop/Loopback standards are for protecting database information in error messages.  I just propagated the database error out the the frontend. 
This is my first time putting in a Pull request for opensource software so guidance about if I'm doing it right or not is appreciated.
Thanks for loopback. It's great
-Abe Barth-Werb
> Ignored Error

- lib/include.js
To replace incorrect location of capturing this condition in find() in
loopback-connector/lib/sql.js  proposed earlier in
https://github.com/strongloop/loopback-connector/pull/34.
Being set to 'includeHasMany', findCaller option triggers injection of
PARTITION BY clause in buildColumnNames() in
loopback-connector-mssql/lib/mssql.js only when find() function is
called to process include filter with 'has many' relation.
> Capture includeHasMany() as a find()'s caller by findCaller option

- lib/dao.js
- test/optional-validation.test.js
make automatic validation optional via CRUD-options or via setting in model definition
@bajtos , @superkhau What should I do with the validateUpsert-option? Which one needs precedence? Now, when explicitly set to false, it has precedence on the new flags, which makes sense IMO
Close #744
> make automatic validation optional

- lib/dao.js
- support/describe-operation-hooks.js
- test/persistence-hooks.suite.js
- `support/describe-operation-hooks.js` - add "loaded" hook to the list of described hooks
- "loaded" hook in DAO.find - set `ctx.data`, not `ctx.instance`
- "persisted" hook in DAO.updateAttributes - report `isNewInstance:false`
- "persist" hook in DAO.updateOrCreate - report `isNewInstance` if the connector provides this info
> Various fixes in operation hooks

- 3.0-RELEASE-NOTES.md
- lib/scope.js
- lib/utils.js
- package.json
- test/async-observer.test.js
- test/init.js
This pr is created for updating files to use `bluebird` as promise library.
Details see here:
Connect to strongloop-internal/scrum-loopback#615
Related: https://github.com/strongloop/loopback/pull/1896
> [SEMVER-MAJOR] Always use bluebird as the Promise implementation

- lib/connectors/memory.js
- lib/dao.js
- test/memory.test.js
Connect to: strongloop/loopback/issues/1864
`Loopback-connector-redis` is one of the connectors, which is not compatible with tests on `loopback-datasource-juggler` and it is expected to fail! For instance, there is no `Null` return value from `Loopback-connector-Redis` and instead it returns empty string and many other incompatibilities,...
> Implement `findOrCreate` for memory connector

- package.json
Rework the test script to call directly mocha and skip Makefile. This allows CI enviroments to detect that this module is using Mocha as the test runner.
Related: 2cdc4ddcbf5 and #767
@jannyHou @rmg I noticed the "npm test" script was changed from `make test` to `mocha` and back, is there any reason why we cannot use the script proposed by this patch?
> Change "npm test" to call mocha directly

- lib/model-builder.js
- lib/model.js
- test/model-definition.test.js
Connect to strongloop-internal/scrum-loopback#642
Hey @bajtos this pr is created for handling `constructor` in two places:
1) Throw error in `/lib/model-builder.js` if model has a property named `constructor`.
2) Give warning in `/lib/model.js` if user assigns property named `constructor` in instance.
Could you review it? Thanks!
Move to this pr since the previous one keep failing even I commented all of my changes. Thanks for your understanding.
> Prevent constructor to be property name

- lib/connectors/memory.js
- lib/dao.js
- test/manipulation.test.js
- test/persistence-hooks.suite.js
See also https://github.com/strongloop-internal/scrum-loopback/issues/621
* Initial implemetation for replaceAttributes method
* Initial implemetation for replaceOrCreate
* These changes are related to the changes in the pull requests under `loopback-connector` and `loopback-connector-mysql`
* It seems test cases cannot be run on windows machines; I need to dig into it.
Connect to a spike task: https://github.com/strongloop-internal/scrum-loopback/issues/621
> Implementation of replaceOrCreate and replace

- lib/datasource.js
WARNING: LoopBack connector "cloudant" is not installed as any of the following modules:
./connectors/cloudant
loopback-connector-cloudant
cloudant
To fix, run:
`npm install cloudant`
to
WARNING: LoopBack connector "cloudant" is not installed as any of the following modules:
./connectors/cloudant
loopback-connector-cloudant
To fix, run:
`npm install loopback-connector-cloudant`
> Fix missing connector error msg for db2, cloudant

- lib/datasource.js
Before this change, after adding a Cloudant-backed datasource to an app, `node .` will fail with
```
AssertionError: url is not valid
(...stack trace...)
```
Now:
```
AssertionError: Cannot initialize connector "cloudant": url is not valid
(...stack trace...)
```
/to @ritch please review
> Improve error message on connector init error

- lib/datasource.js
- test/discovery.test.js
- test/mock-connectors.js
Some database connectors need to have custom field settings.  E.g. Hbase has column families which could be different on a per field basis.  Reading/writing to Hbase is not possible without knowledge of the column families, so this is an important detail to be captured in schema discovery.
Right now, there is a namespace reserved for the connector, but it is hard coded to only populate certain properties.  I'd like to extend that to support any additional properties the connector may need.
A sample discoverModelProperties result for the 'custom' connector might look like this:
```javascript
[
{
owner: 'public',
columnName: 'name',
type: 'String',
required: false,
custom: {storage: 'quantum'}
}
]
```
And discoverSchemas:
```javascript
{
"public.person": {
"name": "Person",
"options": { …
```
> support custom field settings under the connector's namespace

- test/manipulation.test.js
If a field does not have any value in `MySQL` (Relational Databases) `findById` or `find` returns `null` for that field, whereas it is undefined in `memory` and `MongoDB` connectors (NoSQL DBs);  
```
Post.findById(post.id, function(err, p) {
if (err) return done(err);
p.should.have.property('content', undefined); // It fails for relational DBs (MySQL) because if a field is missing value it returns null
should.not.exist(p.comments); // It passes
...
});
```
Actually I did this [PR#788](https://github.com/strongloop/loopback-datasource-juggler/pull/788) in `loopbakc-datasource-juggler` after finishing my [PR#139](https://github.com/strongloop/loopback-connector-mysql/pull/139) in `loopback-connector-mysql` and noticed these test cases in `loopback-datasource-juggler` will be breaking …
> Fix tests for mysql

- test/memory.test.js
- test/persistence-hooks.suite.js
This patch takes care of compatibility issues for Mongodb v2.4 tests for PR: https://github.com/strongloop/loopback-connector-mongodb/pull/202
Please see the next comment for my conversation with Raymond.
@bajtos could you please review this patch.
Thanks  :-)
> Fix Mongo compatibility issue

- lib/datasource.js
- test/discovery.test.js
When I run `ds.discoverSchema` with the Postgres adapter and I provide a table that does not exist, the method hangs.  I would expect it to return an error.
Here is what's happening in the code.  `ds.discoverSchema` calls `ds.discoverSchemas`.  When the latter runs, it [detects that there are no columns returned, so it calls its callback](https://github.com/strongloop/loopback-datasource-juggler/blob/486c1de1ba4572f810606be1aa148db4d272e52c/lib/datasource.js#L1306-L1310).  When `ds.discoverSchema` [receives the value undefined for `schemas`, it tries to iterate through it](https://github.com/strongloop/loopback-datasource-juggler/blob/486c1de1ba4572f810606be1aa148db4d272e52c/lib/datasource.js#L1227-L1236).  Because of whacky not-as-you-would-expect Javascript behavior, this doesn't throw …
> ds.discoverSchema hangs when provided an invalid table name

- lib/dao.js
- test/manipulation.test.js
* Define `patchOrCreate` as an alias for `updateOrCreate`
* Define `PatchAttributes` as an alias for `updateAttributes`
Connect to: https://github.com/strongloop-internal/scrum-loopback/issues/753
@bajtos Please review. Thanks!
> Define `patch` aliases

- test/helpers/context-test-helpers.js
- test/helpers/hook-monitor.js
- test/helpers/uid-generator.js
- test/persistence-hooks.suite.js
This is a preparatory work for #497, where I would like to start a new source file for operations hooks for embedded relations. In order to do that, I need to share helper methods for recording and comparing context objects. In this patch, I am moving helpers to a file that can be loaded from multiple places.
The patch is quite large, as I was not able to preserve the current API which was relying on closures. Sorry for that :(
Connect to #497
/to @superkhau or @Amir-61 please review
> test: extract context-test-helpers

- lib/dao.js
- test/optional-validation.test.js
This patch fixes `forceId` check for `replaceById` method:
Validation fails if you pass `{ forceId: true }` for `replaceById` even though you don't pass the primary key in data object.
Relate to https://github.com/strongloop/loopback-datasource-juggler/pull/893
This ptach (PR#896) needs to be landed before https://github.com/strongloop/loopback-datasource-juggler/pull/893
> Fix `forceId` check for `replaceById`

- test/manipulation.test.js
* Test coverages for hashed password for replaceAttributes
* Test coverages for hashed password for updateAttribute
Connect to strongloop/loopback-datasource-juggler#896
https://github.com/strongloop/loopback-datasource-juggler/pull/896 needs to be landed before this patch (PR#893)
@bajtos: Please review... Thanks!
> Test coverages for hashed password

- examples/app-noschema.js
- examples/app.js
- lib/connectors/memory.js
- lib/dao.js
- lib/include.js
- lib/include_utils.js
- lib/introspection.js
- lib/relation-definition.js
- lib/transaction.js
- package.json
- support/describe-operation-hooks.js
- test/basic-querying.test.js
- test/hooks.test.js
- test/include.test.js
- test/include_util.test.js
- test/loopback-dl.test.js
- test/manipulation.test.js
- test/memory.test.js
- test/optional-validation.test.js
- test/persistence-hooks.suite.js
- test/relations.test.js
- test/scope.test.js
Upgrade eslint-config-loopback to ^2.0.0.
Remove extra empty lines to make `npm run lint` pass again.
@superkhau @Amir-61 PTAL
> eslint config 2.0 + remove extra empty lines

- lib/relation-definition.js
- test/helpers/hook-monitor.js
- test/operation-hooks.suite/embeds-one-create.suite.js
- test/operation-hooks.suite/embeds-one-destroy.suite.js
- test/operation-hooks.suite/embeds-one-update.suite.js
- test/operation-hooks.suite/index.js
- test/persistence-hooks.suite.js
create() triggers
- before save
- after save
udpate() triggers
- before save
- after save
destroy() triggers
- before delete
- after delete
The implementation here is intentionally left with less features
than the regular DAO methods provide, the goal is to get a partial
(but still useful!) version released soon.
Connect to #497 
See the original implementation proposed by @fabien in #516
/to @raymondfeng @Amir-61 please review
**Things left out**
- `before save` and `after save` hooks should include `ctx.isNewInstance`
- Async validations are not supported yet
- `persist` and `loaded` hooks are not triggered at all
- Updating embedded instances triggers update of the parent (owning) model. The context provided by `before save` and `after save` hooks on the parent model is sort of …
> Implement operation hooks for EmbedsOne methods

- lib/relation-definition.js
- test/operation-hooks.suite/embeds-many-create.suite.js
- test/operation-hooks.suite/embeds-many-destroy.suite.js
- test/operation-hooks.suite/embeds-many-update-by-id.suite.js
create() triggers
- before save
- after save
updateById() triggers
- before save
- after save
destroy() triggers
- before delete
- after delete
The implementation here is intentionally left with less features
than the regular DAO methods provide, the goal is to get a partial
(but still useful!) version released soon.
Limitations:
- `before save` & `after save` hooks don't provide `ctx.isNewInstance`
- async validations are not supported yet
- `persist` and `loaded` hooks are not triggered at all
- `before delete` hook does not provide `ctx.where` property and
it's not possible to change the outcome of `destroy()` using this
hook. Note that regular DAO does support this.
- updating embedded instances triggers update of the parent (owning)
model, which is correct and expected. However, the …
> Implement operation hooks for EmbedsMany methods

- lib/dao.js
It was previously completely undocumented. There are additional methods that add promises but I figure accurately documenting some is better than none. 😸
> Document promise support for DAO::find

- lib/dao.js
- test/manipulation.test.js
* The goal is to to achieve the following behaviour for missing values:
db | replaceById / replaceAttributes | replaceOrCreate
--- | --- | ---
*NoDQL (MongoDB)* | undefined| undefined
*NoSQL (Memory)* | undefined   |  undefined
*SQL DBs (Mysql)* |  undefined|   undefined
dependencies' tests | status
--- | --- | ---
*Loopback-connector-Mysql* | Aborted! [1] 👎 
*Loopback-connector-MSsql* | passed 👍 
*Loopback-connector-Oracle* |  passed 👍 
*Loopback-connector-Postgressql* |  passed 👍 
*Loopback-connector-mongodb* |  passed 👍 
*Loopback-connector-redis* |  passed 👍 
*Loopback-datasource-juggler* |  passed 👍 
*Loopback-connector-sqllite* |  first time failed, but second time passed [2] 👎 
[1]:[Here](http://ci.strongloop.com/job/loopback-connector-mysql/label=ubuntu-0.12/1250/console), The …
> Fix incompatibility between different connectors for replace methods

- 3.0-RELEASE-NOTES.md
- lib/mixins.js
- test/mixins.test.js
> [SEMVER-MAJOR] throw error for undefined mixin

- lib/model-builder.js
- test/loopback-dl.test.js
- test/relations.test.js
This is a cleaned up version of #940 
The setting controls the strict mode used for embedded property types, for example the type of "address" property in this model definition:
modelBuilder.define('TestEmbedded', {
name: 'string',
address: {
street: 'string',
},
});
Close #940, fix #923
> ModelBuilder: add new setting strictEmbeddedModels

- lib/dao.js
Return error if the connector returns an error for updateOrCreate
Connect to https://github.com/strongloop/loopback-datasource-juggler/issues/914
Note: It needs to be back-ported to 2.x.
\To: @bajtos
> Retun err for UPSERT if the connector returns err

- lib/dao.js
- test/manipulation.test.js
* Fix error message when PK is changed in `replaceById`
Connect to https://github.com/strongloop/loopback-datasource-juggler/pull/953
> Fix error message

- lib/dao.js
- lib/model-builder.js
- test/manipulation.test.js
* Avoid changing PK for `instance` in `before save` operation hook for replaceById when forceId is set
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/833
*Note: It needs to be back-ported to 2.x.*
To: @bajtos
> Avoid changing PK of instance in operation hook when forceId is set

- lib/dao.js
- lib/model-builder.js
- test/manipulation.test.js
* Give warning if PK is changed in `before save` and `loaded`
operation hooks for replaceById
Connect to https://github.com/strongloop/loopback-datasource-juggler/pull/952
> Give warning if PK is changed in hooks

- lib/datasource.js
Return a real Error message for the default ping() method.
Connect to https://github.com/strongloop/loopback-datasource-juggler/pull/960
Talked to @ritch and since [his PR](https://github.com/strongloop/loopback-datasource-juggler/pull/960) on master got LGTM, now I'm back-porting to `2.x`.
> Updata datasource.js 2.x

- 3.0-RELEASE-NOTES.md
- lib/model-builder.js
- lib/model.js
- test/model-definition.test.js
Result of Compat Flags Clenup.
Throws an error for property names with dots, instead of a deprecation warning.
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/765
> [SEMVER-MAJOR] Throw Error for property names with dots

- lib/dao.js
- lib/validations.js
- test/validations.test.js
This PR fixes issue #984.
When calling isValid for validation from dao, I pass the options parameter and propagate it in validators. Validators then, use it in order to do there potential requests. Doing this way, we do the validation request in the same context than the original request => potential same transaction.
This PR is critical as until now, loopback is not suitable for production with postgres due to transaction concurrency issues. (My prod is down 😄) See issue #984
Duplicate of PR #985 with an appropriate target
> Fix #984 Give request options(ex: transactions) to validators

- 3.0-RELEASE-NOTES.md
- lib/datasource.js
Result of compat flag cleanup.
- Current implementation has a wrapper
DataSource.registerType() for
ModelBuilder.registerType(). This removes
the wrapper to encourage use of original
method.
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/766
> [SEMVER-MAJOR] Remove DataSource.registerType()

- lib/dao.js
- test/basic-querying.test.js
When post-processing result of find operation, use "async.map" instead of "async.each + array.push" to ensure the order of items is preserved.
This work is based on #864, but preserves parallel post-processing.
Fix #800 
@Amir-61 please review
cc @MichaelKohler
> Ensure stable order of items in DAO.find()

- lib/dao.js
- test/basic-querying.test.js
When post-processing result of find operation, use "async.map" instead of "async.each + array.push" to ensure the order of items is preserved.
This is a back-port of #996.
The code has diverged between 2.x and master, the merge leave too many conflicts, so I had to re-do the change again.
/to @Amir-61 please review
/cc @jannyHou @MichaelKohler
> Ensure stable order of items in DAO.find() [2.x]

- test/datatype.test.js
Add a test in `datatype.test.js` to catch invalid date property (see strongloop/loopback#1035).
> Add test to catch invalid date property

- lib/relation-definition.js
Due to undefined `definition` the following line was broken; this is a fix to declare `definition` which is used in the following error message:
```
cb(new Error('BelongsTo relation ' + definition.name + ' is empty'));
```
/to: @jannyHou
/CC: @bajtos
> Declare `definition`

- lib/relation-definition.js
* Declare `definition` in `BelongsTo.prototype.destroy`
Backport https://github.com/strongloop/loopback-datasource-juggler/pull/1009
CC: @jannyHou
> Declare definition[2.x]

- test/manipulation.test.js
Fix a test case that coerces date types but it is incorrectly described to boolean types.
Signed-off-by: Supasate Choochaisri <supasate.c@gmail.com>
> Fix test case typo

- lib/include.js
Optimise related model queries
No longer query for the related/included model when no results are obtained in the first query
fix: https://github.com/strongloop/loopback-datasource-juggler/issues/1006
> Optimize related model queries

- 3.0-RELEASE-NOTES.md
- lib/dao.js
- test/manipulation.test.js
BREAKING CHANGE
@bajtos, please review.
connect to strongloop/loopback#2123
> [SEMVER-MAJOR] Disallow bulk updateOrCreate.

- index.js
- lib/connectors/kv-memory.js
- lib/datasource.js
- lib/kvao/expire.js
- lib/kvao/get.js
- lib/kvao/index.js
- lib/kvao/set.js
- test/kv-memory.js
- test/kvao.suite.js
- test/kvao/_helpers.js
- test/kvao/expire.suite.js
- test/kvao/get-test.suite.js
Models attached to a KeyValue connector get the following *static*
methods:
Color.set(key, value);
Color.set(key, value, ttl);
Color.set(key, value, { ttl: ttl });
Color.get(key);
Color.expire(key, ttl);
This is back-port of #1023
/cc @superkhau
> Implement KeyValue API and memory connector [2.x]

- lib/validations.js
Correct documentation for `validatesFormatOf`
Connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1025
Since it is a small fix I will land it without reviewing.
/CC: @bajtos
> Update doc for `validatesFormatOf`

- lib/datasource.js
- test/crud-with-options.test.js
- test/default-scope.test.js
- test/loopback-dl.test.js
- test/manipulation.test.js
- test/relations.test.js
Connect to strongloop/loopback-datasource-juggler#849
Fix this scenario:
> With REST put and post requests ID property should be ignored otherwise this can result in the following security issue:
attacker creates an instance of some model though rest with maximum possible ID value for the database (e.g. 2^31 for 32bit ints).
It's impossible to add any data anymore since autoincrement would overflow.
the system is broken
I believe this is a serious problem.
For NoSQL database, which doesn't has auto-increment Id, the default `forceId` is undefined.
While for id auto-increment database, the default `forceId` is true, only `settings.forceId` can override it.
> forceId=true with auto-increment db

- lib/dao.js
* Return error if the connector does not implement `replaceById`
While QA was testing replace* methods for Cloudantdb where we do not have support, they got the following error:
```
lavens-mbp:replaceDemo laven$ node .
assert.js:90
throw new assert.AssertionError({
^
AssertionError: replaceById() must be implemented by the connector
at Function.DataAccessObject.replaceById (/Users/laven/Desktop/replaceDemo/node_modules/loopback-datasource-juggler/lib/dao.js:2640:3)
at /Users/laven/Desktop/replaceDemo/node_modules/loopback-datasource-juggler/lib/dao.js:807:16
at /Users/laven/Desktop/replaceDemo/node_modules/loopback-datasource-juggler/lib/dao.js:1824:5
at /Users/laven/Desktop/replaceDemo/node_modules/loopback-datasource-juggler/lib/dao.js:1752:9
at …
```
> Return error if the connector does not implement

- lib/dao.js
* Return error if connector does not implement replaceById
* This patch is without globalization 
Backport https://github.com/strongloop/loopback-datasource-juggler/pull/1034
**Note:**
Please note this patch is without globalization because the globalization backport will go on top of that; the reason is after landing this PR, I got permission from @bajtos to release a new NPM version with `minor` changes and after releasing the NPM version, I will land [PR#1029](https://github.com/strongloop/loopback-datasource-juggler/pull/1029) to backport globalization, which we prefer to happen after releasing NPM version.
/to: @superkhau 
Thanks!
> Return error if connector does not implement

- lib/connectors/kv-memory.js
- test/kv-memory.js
Fix bug in "_setupRegularCleanup()" where the interval callback was trying to access an object that has been garbage-collected in the meantime.
Symptoms:
```
/Users/bajtos/src/loopback/loopback/node_modules/loopback-datasource-juggler/lib/connectors/kv-memory.js:35
function() { self._removeExpiredItems(); },
^
TypeError: self._removeExpiredItems is not a function
at Timeout.<anonymous> (/Users/bajtos/src/loopback/loopback/node_modules/loopback-datasource-juggler/lib/connectors/kv-memory.js:35:23)
at Timeout._repeat (/Users/bajtos/src/loopback/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
at Timeout.wrapper [as _onTimeout] (timers.js:417:11)
at Timer.unrefdHandle (timers.js:454:14)
```
@superkhau please review
> kv-memory: fix crash in regular cleanup

- lib/connectors/kv-memory.js
- test/kv-memory.js
Fix bug in "_setupRegularCleanup()" where the interval callback was trying to access an object that has been garbage-collected in the meantime.
back-port of #1039
> kv-memory: fix crash in regular cleanup [2.x]

- test/kvao.suite.js
When running the tests on Node v0.10, setup `global.Promise` with Bluebird implementation. That way we don't have to run this setup in the test suite of each kv connector.
@superkhau PTAL
Related: https://github.com/strongloop/loopback-connector-kv-redis/pull/5
> test/kvao: setup global.Promise on Node v0.10 [2.x only]

- lib/connectors/memory.js
- lib/dao.js
- test/crud-with-options.test.js
- test/manipulation.test.js
- test/persistence-hooks.suite.js
Added a new method for performing upsertWithWhere in dao.js
Connect to strongloop/loopback#2331
Connect to https://github.com/strongloop/loopback/pull/2539
> upsertWithWhere method

- .npmignore
- lib/connectors/kv-memory.js
- lib/kvao/index.js
- lib/kvao/iterate-keys.js
- lib/kvao/keys.js
- package.json
- test/kvao/_helpers.js
- test/kvao/iterate-keys.suite.js
- test/kvao/keys.suite.js
Add a core implementation of KVAO.iterateKeys() which returns an
AsyncIterator, inspired by
- https://github.com/tc39/proposal-async-iteration
- https://www.npmjs.com/package/async-iterators
This way we can safely iterate even large sets of data.
Also add KVAO.keys(), a sugar API converting the result of iterateKeys()
into a single array.
@superkhau @ritch please review
~~The patch is describing `filter.match` option that's not implemented. I'll either add it to this patch or submit a new one, depending on the speed of code reviews.~~
Connect to strongloop/loopback#2592
> kvao: add iterateKeys() and keys()

- lib/dao.js
- test/persistence-hooks.suite.js
Notify find 2.x
We already implemented `notify` for `find` on master branch; however the implementation of `find` is very different from the one on `2.x`, hence a simple cherry-pick was not going to work; this patch implements `notify` for `2.x`
> Notify find 2.x

- lib/datasource.js
This PR fixes our CI for now for an old issue which has always been there but unnoticed and using `use strict` has discovered the problem/bug.
```
Cannot assign to read only property 'type' of number
TypeError: Cannot assign to read only property 'type' of number
at DataSource.defineForeignKey (node_modules/loopback-datasource-juggler/lib/datasource.js:1833:37)
at Function.hasMany (node_modules/loopback-datasource-juggler/lib/relation-definition.js:638:24)
at Function.hasMany (node_modules/loopback-datasource-juggler/lib/relations.js:74:29)
at Context.defineProductAndCategoryModels (test/relations.integration.js:53:14)
```
Connect to https://github.com/strongloop/loopback-datasource-juggler/pull/1062
> Fix CI introduced by `use strict`

- test/memory.test.js
Let the operation-hook tests use the real implementation, now that we have it in place.
@Amir-61 please review
> test/memory: remove dummy findOrCreate impl

- test/memory.test.js
Let the operation-hook tests use the real implementation, now that we have it in place.
This is a back-port of #1063 
cc @Amir-61
> test/memory: remove dummy findOrCreate impl [2.x]

- lib/connectors/kv-memory.js
- test/kvao/expire.suite.js
The expire feature is falsely returning 204 instead of 404 because it is not
removing expired items before execution.
> Remove expired items before executing expire

- test/kvao/expire.suite.js
Forwardport of #1074. #1072 was missing Promise.resolve before using delay(20)
and causing Travis to fail on 2.x. This PR makes the test code consistent on
both master and 2.x.
@bajtos Merging without review as this is a simple fix for #1072 which has already been reviewed.
> Fix test case for expire

- package.json
This a duplicate entry as the correct ESLint configs are already listed as
devDepencies.
@bajtos PTAL
> Remove ESLint from dependencies

- lib/connectors/memory.js
- lib/dao.js
- test/crud-with-options.test.js
- test/manipulation.test.js
- test/persistence-hooks.suite.js
* Implements updateOrCreateWithWhere
Backport from https://github.com/strongloop/loopback-datasource-juggler/pull/1001
> upsertWithWhere feature support in juggler DAO [2.x]

- test/kvao/ttl.suite.js
Reduce the complixity in the TTL test suite for the kv-memory connector to
get CI to pass. This change makes 3.x tests equivalent to 2.x tests (which are already merged and passing on CI).
- Tests messages were reworded and reorganized to make the scope of each test clearer
- Some of the code refactoring was done to make CI pass (the original tests were failing due to some expiry issue)
Forwardport of #1077
> Refactor TTL tests for KV memory connector

- lib/connectors/kv-memory.js
- test/kvao/expire.suite.js
The expire feature is falsely returning 204 instead of 404 because it is
not removing expired items before execution.
Backport of #1072
> Remove expired item before executing expire

- lib/connectors/memory.js
- test/memory.test.js
Enhance the built-in memory connector to correctly support nested
queries for arrays in addition to objects.
E.g. if "friends" is an array of objects containing "name", then
{ where: { "friends.name": "Jane" } } should match records containing
a friend called "Jane".
Forward-port #1027, implement https://github.com/strongloop/loopback/issues/2582.
> Support nested queries for arrays

- test/kvao/ttl.suite.js
Fix regression introduced by #1078 that caused loopback-connector-kv-redis tests to fail.
cc @superkhau
> Add missing "done" arg in test/kvao/ttl.suite

- 3.0-RELEASE-NOTES.md
- lib/dao.js
- lib/model.js
- lib/validations.js
- test/datatype.test.js
- test/loopback-dl.test.js
- test/manipulation.test.js
connect to strongloop/loopback/issues/1299
> [SEMVER-MAJOR] Strict mode cleanup

- lib/dao.js
- test/memory.test.js
- test/persistence-hooks.suite.js
* Add 'isNewInstance' to loaded hook for updateAttributes
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/1030
Need to be back-ported as well.
/to: @superkhau 
/cc: @bajtos
> Add 'isNewInstance' for updateAttributes

- lib/validations.js
Trailing spaces in comments causing linter to fail. Errors introduced
at commit 9a1ef0849575a124f963ceb2043916b0b89fbf40.
cc @Amir-61 @crandmck @strongloop/fa-db-connectors
> Fix linting errors

- lib/connectors/memory.js
- lib/dao.js
- test/basic-querying.test.js
- test/init.js
> Add ilike and nilike operators

- lib/dao.js
- test/persistence-hooks.suite.js
Fix the bug when `near` filter is used
* If near filter was used, users would get:
```
Error: Callback was already called
```
Connect to https://github.com/strongloop/loopback-connector-mongodb/issues/285
/to: @bajtos
> Fix the bug when near filter is used

- test/helpers/bdd-if.js
- test/kvao.suite.js
- test/kvao/expire.suite.js
- test/kvao/get-set.suite.js
- test/kvao/iterate-keys.suite.js
- test/kvao/keys.suite.js
- test/kvao/ttl.suite.js
- canExpire
- canQueryTtl
- ttlPrecision
- canIterateKeys
- canIterateLargeKeySets
These options allow connectors to disable shared tests for features that are not supported/implemented.
Connect to strongloop-internal/scrum-loopback#1128
See also the spike - #1129
@superkhau please review
> test/kvao: add connectorCapabilities options

- test/helpers/bdd-if.js
- test/kvao.suite.js
- test/kvao/expire.suite.js
- test/kvao/get-set.suite.js
- test/kvao/iterate-keys.suite.js
- test/kvao/keys.suite.js
- test/kvao/ttl.suite.js
- canExpire
- canQueryTtl
- ttlPrecision
- canIterateKeys
- canIterateLargeKeySets
These options allow connectors to disable shared tests for features that are not supported/implemented.
Back-port #1140 
Connect to strongloop-internal/scrum-loopback#1128
See also the spike - #1129
> test/kvao: add connectorCapabilities options [2.x]

- lib/validations.js
- test/validations.test.js
is defined.
Connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1106
Thinks to note:
- This fix needs to be applied to many other validations too. Only did validateNumericality for now.
- I don't know how much we care about performance, but checking each attribute for each validator if it's type is undefined is maybe not the best approach. Still, this was already done before with nullCheck() and should be better, but still not perfect.
- In the original check the validator only checked if the attribute is typeof 'number'. But we also need to check that attribute is not NaN. Because typeof NaN => 'number'.
> validateNumericality should skip undefined

- lib/dao.js
- test/loopback-dl.test.js
I discovered this while working on https://github.com/strongloop/loopback/issues/2824 and felt it needed to be fixed. Please let me know if there's some non-obvious reason why logical operators should halt coercion.
> DataAccessObject._coerce now continues after encountering a logical op

- lib/dao.js
- test/loopback-dl.test.js
Backport of https://github.com/strongloop/loopback-datasource-juggler/pull/1142
/to: @doublemarked
/cc: @superkhau @bajtos
> Continue _coerce after logical operators

- lib/dao.js
- test/persistence-hooks.suite.js
* Add support for `loaded` operation hook for DAO.find() when near is used
Connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1135
> Add support for `loaded` operation hook for DAO.find() when near is used

- package.json
loopback-connector-informix
loopback-connector-mssql
loopback-connector-mqlight
loopback-connector-oracle
Those four connectors have existing failures that causing downstream CI fail.
Details see: https://github.com/strongloop/loopback-datasource-juggler/pull/1153#issuecomment-263935537
> Add some connectors to ignoreList

- package.json
- Remove Microsoft SQL connector
- Remove Oracle connector
@jannyHou We know these connectors should be fully functional on CI, removing from downstream ignore list. The real solution is to pass those issues you create to fix CI to the relevant squad leads to get it planned/interrupted if necessary.
> Remove valid connectors from downstream ignore list

- lib/include.js
- lib/scope.js
- lib/utils.js
- test/relations.test.js
Connect to strongloop/loopback-datasource-juggler#166
Scenario:
```js
// Physician hasMany Patients through Appointment
physician.patients({ 
order: 'name',
limit: 5,
skip: 1,
offset: 1,
fields: 'date'
}, function(err, cb));
```
When through model exists, the filter should be applied to related model instead of through model.
> Apply filter on related model 

- test/persistence-hooks.suite.js
loopback-connector-mysql is red on juggler CI
This PR is the fix for this failure. 
This PR is prerequisite for https://github.com/strongloop/loopback-connector-mysql/pull/211
> Fix MySql CI server Failure

- examples/datasource-app.js
- lib/connectors/memory.js
- package.json
- test/basic-querying.test.js
- test/crud-with-options.test.js
- test/datatype.test.js
- test/default-scope.test.js
- test/defaults.test.js
- test/hooks.test.js
- test/include.test.js
- test/json.test.js
- test/loopback-dl.test.js
- test/manipulation.test.js
- test/optional-validation.test.js
- test/persistence-hooks.suite.js
- test/relations.test.js
- test/schema.test.js
- test/scope.test.js
- test/validations.test.js
- eslint ^3.11.1
- eslint-config-loopback: ^6.0.0
- fix linter errors (mostly no-undef)
@superkhau or @Amir-61 please review
> Upgrade eslint & config to latest

- examples/datasource-app.js
- lib/connectors/memory.js
- test/manipulation.test.js
- test/persistence-hooks.suite.js
Back-port the relevant parts of #1179
cc @superkhau @Amir-61
> Back-port fixes for linter errors from master

- lib/dao.js
- test/allow-extended-operators.test.js
Modify the coercion of filter.where to hounour "allowExtendedOperators" and don't coerce property values of type object (extended operators). This allows MongoDB users to query using MongoDBs operators like `{ $exists: true, $ne: null }`.
See https://github.com/strongloop/loopback/issues/646
@raymondfeng @superkhau or @Amir-61 please review
@fabien IIRC, you are using MongoDB quite a lot. Could you please take a look too?
> Honour allowExtendedOperators in "DAO.find"

- lib/connectors/kv-memory.js
- lib/kvao/flush.js
- lib/kvao/index.js
- test/kvao/flush.suite.js
Used to delete all keys (and values) associated to the current model.
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/1379
cc @bajtos
> Add flush operation to KVAO

- lib/datasource.js
- test/relations.test.js
Defining a model relation with the name "trigger" causes the model not
able to insert records. No error is thrown when a model relation with
the name "trigger" is defined. Adding a check for the model relation
name "trigger" will now throw an error.
@bajtos This was originally submitted for a fix in strongloop/loopback#2988. Per your request to apply the patch to this repository. Please review.
> Throw error when model relation name is trigger

- lib/datasource.js
- test/relations.test.js
Defining a model relation with the name "trigger" causes the model not
able to insert records. No error is thrown when a model relation with
the name "trigger" is defined. Adding a check for the model relation
name "trigger" will now throw an error.
Backport #1204 
cc @schempy
> Throw error when model relation name is trigger [2.x]

- lib/dao.js
- test/loopback-dl.test.js
Fixes https://github.com/strongloop/loopback/issues/2824
Please let me know if this is aligned with your goals for `DataAccessObject._coerce`.
> Coercing conditions with array-like objects into arrays

- lib/dao.js
- test/loopback-dl.test.js
The query-string parser used by express
https://github.com/ljharb/qs#parsing-arrays
limits the size of arrays that are created from query strings to 20
items. Arrays larger than that are converted to objects using numeric
indices.
This commit fixes the coercion algorithm used by queries to
treat number-indexed objects as arrays. We still maintain a strict
understanding of an "array-like object" to limit the opportunity for
subtle bugs. In particular, the presence of non-index keys is an
indication that the object was not intended to be interpreted as
an array.
back-port #1143, fix strongloop/loopback#2824
cc @doublemarked
> Coerce array-like objects into arrays

- test/kvao/_helpers.js
- test/kvao/delete-all.suite.js
- test/kvao/delete.suite.js
- test/kvao/expire.suite.js
- test/kvao/get-set.suite.js
- test/kvao/iterate-keys.suite.js
- test/kvao/keys.suite.js
- test/kvao/ttl.suite.js
Clear CacheItem data between tests if connector supports `deleteAll`. Tests fail with 501 if this check is not used.
> Detect deleteAll support in KVAO tests

- lib/model.js
- lib/transaction.js
- package.json
Replace deprecated `node-uuid` with `uuid`.
- None
> Replace deprecated node-uuid with uuid module

- lib/model.js
- lib/transaction.js
- package.json
Upgrade dependencies to remove warnings from `npm install`.
- #1227
> Upgrade dependencies to remove npm install warnings

- test/basic-querying.test.js
While investigating https://github.com/fuwaneko/loopback-connector-rethinkdb/issues/10, I found that the shared test suite does not have any tests covering the `inq` operator. This patch adds two basic tests for a started.
@superkhau PTAL
> Add two basic tests for "inq" operator

- examples/app.js
- examples/load-schemas.js
- lib/connectors/kv-memory.js
- lib/connectors/memory.js
- lib/dao.js
- lib/list.js
- lib/relation-definition.js
- lib/utils.js
- package.json
- test/include.test.js
- test/operation-hooks.suite/embeds-many-destroy.suite.js
- test/persistence-hooks.suite.js
- test/relations.test.js
- test/validations.test.js
The first commit fixes option propagation in the following two relation methods:
- EmbedsMany.prototype.remove
- EmbedsMany.prototype.add
The second commits upgrade eslint config to latest and fixes remaining issues reported by eslint.
-  strongloop/eslint-config-loopback#19
> Upgrade eslint-config, fix new violations

- test/manipulation.test.js
Add a test case to ensure that replaceById will return error 404 when id does not exist in db. 
- reference:
https://github.com/strongloop/loopback-connector/pull/73#issuecomment-275041949
connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1244
> Ensure replaceById returns 404 when id not found

- lib/datasource.js
- package.json
- test/datasource.test.js
- test/fixtures/loopback-connector-throwing/index.js
- test/fixtures/loopback-connector-throwing/package.json
Before this change, when resolving full connector path, all errors were
ignored. As a result, when the connector was installed but not
correctly built (e.g. loopback-connector-db2 which uses a native addon),
a very confusing message was reported by LoopBack.
In this commit, I am fixing the code handling `require()` errors
to ignore only MODULE_NOT_FOUND errors.
- None
This problem resurfaced when troubleshooting client installation, cc @kjdelisle @qpresley.
> Fix datasource to report connector-loading errors

- lib/dao.js
- test/optional-validation.test.js
Fixed a bug preventing an error stack to display proper input values.
- strongloop/loopback-connector-mysql/#216
> Fix error message formatting when trying to update an id property

- package.json
This breaks our repo scanner, but since it is actually invalid the way it is I'm opting to fix it here instead of in the scanner.
> fix incorrect engines property in package.json

- test/basic-querying.test.js
when !order, it returns empty string causing a failing test case. 
connect to https://github.com/strongloop/loopback-connector-oracle/issues/123
test case in` loopback-datasoruce-juggler/basic-query.test.js`
> Fix Order query test case

- lib/dao.js
- test/basic-querying.test.js
- test/manipulation.test.js
Wrap inst.setAttributes in try-catch to prevent synchronous errors
from crashing the application.
#1247 
> dao: catch sync errors on setAttributes

- test/default-scope.test.js
Add collection name settings for arangodb database.
Required to pass common tests included in community connector
- imported tests fail on https://github.com/mrbatista/loopback-connector-arangodb/pull/44
> Override collection name for arangodb connector

- lib/dao.js
- test/loopback-dl.test.js
When declaring a property in model definition JSON as `object` type and initialize a model that has this property as an empty object, it gets converted to an empty array. coerceArray misses check for empty Object type. This results into false program logic where checks are made for object and find an array
#1230 
> Fixes #1230 coerceArray converts empty Objects to array

- lib/dao.js
Add the error callback in FindOrCreate.
PR for 2.x has been merged: https://github.com/strongloop/loopback-datasource-juggler/pull/1226
This PR is for 3.x. 
https://github.com/strongloop/loopback-datasource-juggler/issues/1223
- None
> FindOrCreate missing error callback

- lib/utils.js
- test/basic-querying.test.js
- test/util.test.js
Fixes the referrenced issue for excluding non existing fields
#1256 
> Using a filter with exclusion of a non existent property, removes an existing one

- lib/include.js
- lib/model.js
- test/include.test.js
Changed behaviour when including related models in find operations forces to change the flag of strict to false, so any change to the model will also save in the datasource tha included properties...
I believe it should not change the default strict setting as in the original model definition
- #1252 
> Included models from include operations do not change defined `strict` model option

- lib/include.js
- test/relations.test.js
`Include` filter takes into consideration string property 'fields' and transforms it into an array containing this string.
- #1275
> Fixes #1275. `Include` filter transforms fields property into array.

- lib/scope.js
- test/relations.test.js
Fix `_targetClass` on scope function when using hasManyThrough relation with customized relation names and foreignKey/keyThrough.
This bug is cause by `_targetClass` uses the camel-case of `relationName`(e.g.: if `relationName` is `bbb`, `targetClass` would be `Bbb`), which is not exists.
This will also suppress "not exposed" warnings when generating angular sdk, and generate end-points for this scope.
- None
> fix _targetClass on scope function

- test/manipulation.test.js
Some connector, like arangodb, not support id as Number.
When `forceId` is set to true and id is set `Model.isValid`
report error and the field id is not coerced.
mrbatista/loopback-connector-arangodb#44
> fix test forceId connector arangodb

- test/manipulation.test.js
Some connector, like arangodb, not support id as Number.
When `forceId` is set to true and id is set `Model.isValid`
report error and the field id is not coerced.
mrbatista/loopback-connector-arangodb#44
> Backport - fix test forceId connector arangodb

- lib/connectors/memory.js
- lib/datasource.js
- test/memory.test.js
During code review of https://github.com/strongloop/loopback-datasource-juggler/pull/1300, we removed the duplicate protection in mem connector but it led to a path to create duplicate connects. This follow-up PR fixes the issue.
- None
> Use dataSource.connect to avoid duplicate connects

- lib/model.js
- test/loopback-dl.test.js
In `model.js` `_initProperties` there's a check on `data.constructor` making sure that it's not a `function`. As @jannyHou already clarified here *https://github.com/strongloop/loopback-datasource-juggler/issues/1261#issuecomment-286838360*, and as stated in the docs *http://loopback.io/doc/en/lb3/Valid-names-in-LoopBack.html#general-rules*, **constructor** is a reserver word.
But looking at the code:
```javascript
if (typeof data !== 'undefined' &&
typeof (data.constructor) !== 'function') {
throw new Error(g.f('Property name "{{constructor}}" is not allowed in %s data', ctor.modelName));
}
```
What if we pass an object like:
```javascript
data = {
name: "this is my name"
}
```
Plain objects will make the condition be **truthy**.
My approach is to check before, if the `data` object has a …
> #1261 Property name "constructor" is not allowed in 'Model' data

- lib/datasource.js
Before when we had more than one FK in `Table A` referencing the primary key in `Table B` it would only return the last foreign key to create a relation. It was simply because it was using the "table_name" to generate the relation name and the last one would overwrite any previous relations with the same "table_name".
- https://github.com/strongloop/loopback-connector-mysql/issues/253
> Support multiple fk relations

- lib/include.js
Fixed 502 if relation object doesn't exist and query entity with remote-connector as datasource.
Can be related to
- #951
> objListis empty in linkOneToMany function

- lib/geo.js
- test/basic-querying.test.js
- test/geo.test.js
Modifies the `geo.nearFilter` to provide an in-depth search (so that it also searches in sub-queries, such as `$and` arrays)
~Requires~ PR strongloop/loopback-connector-mongodb#322 *helps make it* work *properly* in MongoDB and ~probably~ similar modifications in other connectors *might help too*.
- Required for PR strongloop/loopback-connector-mongodb#322
- Based on strongloop/loopback-datasource-juggler#993
> "Near" fix for where clauses

- lib/dao.js
- test/persistence-hooks.suite.js
This change sends the `info` object, which contains the count of records updated to the `after save` hook. Currently this information is returned in the callback / Promise from an update, but it is not sent to the after-save hook. This PR fixes that.
- None
> Allow `after save` hook to see count of records changed

- test/relations.test.js
Recreate PR to see how the downstream connectors build with the Cassandra support.
- None
> Make tests work for other connectors as well as C*

- test/manipulation.test.js
Unskipping test case that was usually failing on mssql connector. 
The test will only be skipped for mssql connector, since the fix in mssql might cause incomptability
More info: https://github.com/strongloop/loopback-connector-mssql/pull/92
connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1305
> Unskip test case

- test/relations.test.js
This Pr https://github.com/strongloop/loopback-connector/pull/100  is failing on the three connectors: `mssql`, `oracle` and  `postgresql`.
EmbedsMany  relation model does not really work with connectors `mssql`, `oracle`, `postgresql`
and the id cannot be found and it generates an error: ` Error: Could not update attributes. Object with id 5 does not exist!`. 
The test case can only see one query where the id is `link.id`, however that id does not exist in the db. 
connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1331
connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1185
https://github.com/strongloop/loopback-datasource-juggler/pull/1304
https://github.com/strongloop/loopback-connector/pull/100
> Alter relations test case

- package.json
* Allows sharing object models between this libary and the others
helping orchestrate this (eg: loopback-connector,
loopback-connector-postgresql)
* EG: All copies of the library will share one
loopback-connector.ParameterizedSQL object
see: https://github.com/AccelerationNet/loopback-connector-postgresql/commit/0661c6c8a0690b0655d2f70a559b3667f41a9c7e
I was unsure how to add tests for this as the bug is only apparent in a full working loopback, but there are possible bugs because the loopback-connector-postgresql creates ParameterizedSQL objects that 
are incompatible with the ones here because both list loopback-connector as a dependency rather than a peerDependency.  If we are sharing object models, they all need to come from one instance of the library rather than from separate ones
- …
> Make this lib peerDepend on loopback-connector

- package.json
Revert back strongloop/loopback-datasource-juggler#1326 due to `loopback` requiring `loopback-connector` as a default dependency through this module.
connect to https://github.com/strongloop/loopback-workspace/issues/487
> Revert "Make this lib peerDepend on loopback-connector"

- lib/model-builder.js
- lib/validations.js
- test/datatype.test.js
- test/manipulation.test.js
- test/validations.test.js
Originated from PR https://github.com/strongloop/loopback-datasource-juggler/pull/718
There's no response from the user to grant me access to his fork, so I've created a separate PR.  User @hotaru355 has signed CLA. 
Excerpt from original PR: 
```
Instantiating a model with an invalid date would not throw an exception, 
but calling isValid() on it would return false, without having to add the validation method explicitly.
```
2 tests are removed because they are no longer valid because no exceptions are thrown when instantiating the model. 
- `should fail if field validation fails` in manipuliation.test.js 
- `throws an error when property of type Date is set to an invalid value` in datatype.test.js
https://github.com/strongloop/loopback-datasource-juggler/pull/718 …
> replace exception thrown for invalid dates

- test/basic-querying.test.js
Unit test for where null and not null against Date types.
Regression test for #1328 and #1334
- None
> Added unit tests specific to DateType where null

- lib/datasource.js
connected to https://github.com/strongloop-internal/scrum-apex/issues/175
> Datasource documentation tune-up

- lib/datasource.js
Update api documents/ js docs and address all REVIEW and FIXME tags
connect to https://github.com/strongloop-internal/scrum-apex/issues/175
> Update api documents

- test/datatype.test.js
Some databases are storing the value in UTC (not ISO) format,
and truncating the values. Even though this is technically
unavoidable, it does fail strict string equality.
> datatype.test: use predefined date

- test/basic-querying.test.js
The order of the instances in the array could be reverted sometimes. That's is causing CI failures sometimes. 
so users[0].name could be 'John Lennon' or Paul McCartney' and the same for users[1].name, 
so the fix is trying to ignore the order of names but to ensure that both names are still there.
> Fix order of query results

- test/basic-querying.test.js
- test/relations.test.js
PR created when recovering test cases in cloudant:
cloudant creates string type id which could not guarantee id are incremented. To solve the problem, I add a `sequence` property to make sure the related test case returns result ordered by sequence and will skip the first data. 
> create sequence for nosql id

- lib/date-string.js
- lib/types.js
- test/date-string.test.js
New type that preserves string input as a string, but ensures that
the string is a valid Date.
Additionally, provides a .toDate function to provide the Date
object representation of the string.
**NOTE**: This PR has changed from its original intent, so if you feel confused, you should know that you're not crazy. :)
https://github.com/strongloop/loopback-connector-mysql/issues/149
> Add DateString type

- docs.json
Add the DateString to the docs.json so that they end up in our API docs.
> docs: add DateString definition

- lib/datasource.js
- lib/relation-definition.js
- test/loopback-dl.test.js
- test/relations.test.js
Fixes `DataSource.prototype.defineRelations()` so that the **short** JSON definition syntax for polymorphic hasMany relation works **as per the doc** :
```js
"relations": {
"pictures": {
"type": "hasMany",
"model": "Picture",
"polymorphic": "imageable"
}
}
```
See in this [separate branch's commit](https://github.com/strongloop/loopback-datasource-juggler/commit/6c1cadd5a0b41c81d489b1143cb34c68c2509dba) : i reworked one existing test that shouldn't pass on master (but actually does, as the result of multiple hacky params manipulation). I [highlighted one test](https://github.com/strongloop/loopback-datasource-juggler/commit/6c1cadd5a0b41c81d489b1143cb34c68c2509dba#diff-110954604350ae6d0d8279e7ede6d5e2R1135) that now fails on master, although it should pass.
**feature flag or not ?**
To me …
> honor polymorphic relations via JSON as in doc

- lib/model-builder.js
- test/exclude-base-props.test.js
@raymondfeng PTAL This PR handles excludeBaseProperties from base 'Model' -   This is for fixing https://github.com/strongloop/loopback-workspace/issues/486
> Handle excludeBaseProperties

- lib/dao.js
connected to https://github.com/strongloop/loopback-connector-cloudant/issues/55
Previously, it would just pass the old data. Need to pass the updated data because cloudant changes the `_rev` property on CRUD call.
> Use correct data on replace callback

- lib/dao.js
- test/manipulation.test.js
The issue was discovered in loopback-next. When an array of values is passed into Model.create() without a callback function, it does NOT return a promise. The PR fixes the issue.
- None
> Return promise for batch create

- test/basic-querying.test.js
There is no guarantee on the order that the array values comes back so sort before asserting value.
- None
> Fix assert as array does not guarantee order

- test/model-inheritance.test.js
Please note there is an injected `id` property from User prototype. We do not care about that property since the `customer` model extends the `User` model and has its own **customerId**. 
connect to https://github.com/strongloop-internal/scrum-apex/issues/209
> Fix count of properties

- lib/dao.js
Currently, the `updateAttributes` callback does not pass through the updated data from the database to juggler.
Allow pass through of the new data from the connector itself and update the context data to have the new `_rev` value got after the update.
Similar to the [replaceCallback in dao](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L3062)
connect to https://github.com/strongloop/loopback-connector-cloudant/issues/35
> Fix updateAttributes cb

- test/basic-querying.test.js
- test/helpers/bdd-if.js
- test/persistence-hooks.suite.js
Differentiate between tests skipped by feature flags, and those
manually marked as skipped.
Tests that use the `bdd.describe` and `bdd.it` helper functions
will be marked as `[UNSUPPORTED]` if they are conditionally disabled.
Annotate all of the tests at the start of the run to indicate which of them has been skipped due to lack of support in the connector (support flags are disabled).
Hopefully, this should also help find tests that are *not* being skipped for those reasons...
- connected to https://github.com/strongloop/loopback-connector-mysql/issues/234
> test/helpers: annotate skipped tests

- lib/scope.js
- test/relations.test.js
Fix the case where qWhere[idKey] is null
https://github.com/strongloop/loopback-datasource-juggler/issues/1381
> Fix the case where qWhere[idKey] is null

- test/manipulation.test.js
connect to strongloop/loopback-connector-cloudant#33
related to https://github.com/strongloop/loopback-connector-cloudant/pull/159
> Skip imcompatible tests

- lib/relation-definition.js
- lib/scope.js
- lib/utils.js
- test/relations.test.js
The `getAsync()` is defined in 3 places: `BelongsTo`, `HasOne` and `HasMany`, which is implemented as a scope. Therefore, it is also present on all scopes.
I find its naming really strange though:
- It is the only function with `Async()` in its name
- Like all other functions on relationships (`create()`, `update()`, `count()`, etc), it accepts a callback function and returns a promise if none is provided.
I would like to suggest to rename it to `find()` for scopes and `HasMany` relationships to mirror `Model.find()`, and `get()` for `BelongsTo` and `BelongsTo` relationships, while keeping the `getAsync()` around for backward compatibility for now. 
@bajtos has pointed me to previous discussions around why `get()` wasn't deemed a good name before here: …
> Rename getAsync() methods to find() and get()

- lib/validations.js
- test/validations.test.js
Allow empty values when allowBlank is true in conjuction with `model.validatesInclusionOf()`. Use case is detailed in related issue below.
#1386 
> #1386 Allow empty values when allowBlank is true

- lib/connectors/memory.js
- test/memory.test.js
Property types defined using empty arrays or objects is not documented behaviour: 
http://loopback.io/doc/en/lb2/LoopBack-types.html#overview
http://loopback.io/doc/en/lb2/LoopBack-types.html#array-types
http://loopback.io/doc/en/lb2/LoopBack-types.html#object-types
This unexpected usage, combined with changes made to the Memory connector in #1361 throws unhandled errors when attempting to parse results from the Memory datasource.
This PR fixes this by clarifying these errors, as well as providing additional test coverage.
> castPropertyValue: throw on malformed types

- lib/dao.js
- test/manipulation.test.js
- test/validations.test.js
Currently, `update`/`updateAll` function does not perform any validation if a validation is specified on the model. This fix adds the validation check on dao for `update`/`updateAll` function and tests with all the [validatable functions](https://loopback.io/doc/en/lb2/Validating-model-data.html#using-validation-methods).
fixes https://github.com/strongloop/loopback-datasource-juggler/issues/771
> Add validation on update

- lib/dao.js
- test/validations.test.js
Previously it would return the object to be updated as a part of the callback even though the data was not updated. This PR makes sure only the **error** is returned if a validation error is caught.
> Fix update validation callback

- lib/validations.js
- test/validations.test.js
Fixes #1437.
This fixes validatesFormatOf so that it van validate numbers as well as strings by extending the `typeof` check to support numbers and casting the value to a string using `toString` prior to running the regex check.
#1437 
#1355
> fix: support numbers in validatesFormatOf

- lib/dao.js
- test/manipulation.test.js
Some methods needs to catch the error using callback, otherwise it may create an error that cannot be caught..
Doing the catch in `setAttributes` did not work .. as well as some methods do not even use `setAttributes` as you can see in the pr. 
This pr is complemented by this one https://github.com/strongloop/loopback/pull/3570
connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1436
> Catch err using Callback

- test/relations.test.js
Add test coverage for hasAndBelongsToMany to ensure that destroyAll() works fine. 
<!--
Please use the following link syntaxes:
connect to https://github.com/strongloop/loopback-datasource-juggler/issues/95
> Add test coverage for hasAndBelongsToMany

- lib/transaction.js
This simple PR is part one of moving the handling of transaction timeouts and ids from `loopback-datasource-juggler`'s [`TransactionMixin.beginTransaction()`](https://github.com/strongloop/loopback-datasource-juggler/blob/3b45c76d0fd3364c55a55720d685b5596fb578d1/lib/transaction.js#L73-L108) to `loopback-connector`'s [`Transaction.begin()`](https://github.com/strongloop/loopback-connector/blob/fd7d5db2c88295ed695162d906220f722a628293/lib/transaction.js#L66-L99), where it makes more sense and can be leveraged more easily by other parts of the code, e.g. the work I am doing in #1472. For a more detailed description of the motivation to do so, see https://github.com/strongloop/loopback-datasource-juggler/pull/1472#issuecomment-324613756
By itself, this does not change anything yet, it just …
> Part 1 of moving tx timeout and id to connector

- lib/validations.js
- test/validations.test.js
The RegExp is cloned before executing the test to ensure that every object is tested against a 'fresh' RegExp-instance. This is especially useful in cases where the RegExp contains a /g-modifier and bulk creates are performed. See the example from issue #1475.
- solves #1475 
> Fix for issue #1475

- lib/dao.js
- lib/datasource.js
- lib/transaction.js
- package.json
- test/transaction.test.js
Based on the way [Objection.js](https://github.com/Vincit/objection.js) is [handling transactions by binding them to models](http://vincit.github.io/objection.js/#binding-models-to-a-transaction), I was looking for a way to do the same in LoopBack. At first I thought I would have to make heavy use of `Proxy` objects, but luckily it turned out that there was already a mechanism in place, but only useable for `memory` and `transient` datasources:
https://github.com/strongloop/loopback-datasource-juggler/blob/6c6df15286400e0dfbc2a458e0a074acc1abeecd/lib/datasource.js#L2068-L2101
It works by making use of `DataSource`'s `copyModel()` which creates a slave model bound to a given data source.
This PR extends this existing infrastructure and adds support for database transactions through the use …
> Add a better way to handle transactions by binding them to models

- lib/model-builder.js
This error was swallowed by strong-remoting try/catch
in `eachRemoteFunctionInObject()`.
`__data` isn't guaranteed to exist here. This removes the need for [this try/catch](https://github.com/strongloop/strong-remoting/blob/5b89fb2ab79a77c5b4d25b4009e8033951eb4852/lib/shared-class.js#L297) on property access.
> fix(model-builder): __data may be undefined.

- lib/model.js
- test/datatype.test.js
Redis connector will pass null back if entity is not found causing `data.constructor` to throw an error. Rather than updating the connector, I figured it's probably best to check for null as well since undefined is already being checked.
- #1486
> Allow passing null to base model ctor

- test/basic-querying.test.js
- test/datatype.test.js
connect to strongloop-internal/scrum-apex#331
Fix the current test failures[part 1].
some connector like postgresql & oracle uses same model name `MyModel` and results in conflict when `automigrate`: creating existing schema `public`
> Fix basic-querying

- lib/relation-definition.js
- test/relations.test.js
Having very little control over embedded properties can be frustrating. My two use-cases for this feature are demonstrated in the tests I have added but basically boils down to setting datasource options on the property.
Cleaner solution would be to make `property` support the property options I suppose but it would be more of a breaking change.
> Allow customizing embedded relation property

- lib/scope.js
- test/relations.test.js
This PR fixes the posibility to query on related models. Please note that all the credits goes to @f0rmiga and @jannyHou who prepared the fix in PR's #1480 and #1491. However, due the fact those PR's are a bit stale, I merged the changes from those two PR's to a single commit (instead of 15 merged commits), because I think this functionality is very welcome in a next release.
- strongloop/loopback#3634
> Fix query for related models

- lib/utils.js
- package.json
- test/util.test.js
The uniq function does currently not work when the database is mongodb. In the case of mongodb, the function will receive an array of bson object of bson type ObjectID. The indexOf function in uniq will return a different index for the same mongodb ID, as it is wrapped in the ObjectID. This results in an array that has duplicate mongodb IDs. This commit first transforms any ObjectID in the given array to a string representation. We can then use indexOf to return unique items.
Replaces PR: https://github.com/strongloop/loopback-datasource-juggler/pull/1418
- connect to #1466
> Fix bug with bson objects in utils uniq function

- lib/datasource.js
@lehni I'd like to get your opinion on this one. The new way of handling transactions that you added was not working for me using `loopback-connector-postgresql`. `tx.observe` was not a function so it was throwing an error.
Inspecting the transaction object you have a few properties, one of which is `connector` which points to `loopback-connector` allowing you to observe timeouts.
- #1494
> Allow new transaction method in postgresql

- lib/model-builder.js
- test/model-builder.test.js
Rework the code building model constructors to leverage `Function` class and dynamically emit a constructor function named after the model.
Before this change, all model classes were called "ModelConstructor", which made debugging difficult.
After this change, a model class for model "User" is called "User" 🎉 🎊 
Because not all valid model names are also valid JavaScript identifiers, we implement a simple sanitization technique to cover most common invalid characters (replacing "-", "." and ":" with underscore "_") and fall back to legacy "ModelConstructor" if the model name is still not a valid JS identifier.
_This issue has been itching me for years! My initial attempt to use `new Function` for emitting model class constructor failed, because I was not able to access `ModelBaseClass` …
> Set model constructor name to model name 

- lib/relation-definition.js
- test/relations.test.js
In a Many-to-Many relationship, it was possible for an authenticated user to edit the foreign keys of records to transfer ownership.
Example:
A Physician has many appointments with many patients.
Physician 1 can create an appointment with Patient 1 via a POST as expected.
Physician 1 can then update the intermediate record and change the FK of phyisicianId to that of a different physician via a PUT request.
Physician 1 will no longer be able to access the record but Physician 2 now has an appointment that wasn't created by that physician.
> fix unauthorized fk change

- .travis.yml
- package.json
Drop support for Node 0.10/0.12 as it’s not supported by Node and tests
are failing since our dependencies no longer support Node 0.10/0.12
blocks #1540
> drop support for node 0.10 / 0.12

- lib/datasource.js
As discussed [here](https://github.com/strongloop/loopback/pull/3733), @bajtos requested I add a warning for datasource objects which have a different name from what is specified in the corresponding settings object. Please let me know if any adjustments are required. Thanks!
- connect to strongloop/loopback#3732
> Add warning for datasources with mismatched names

- lib/datasource.js
- test/datasource.test.js
Data source names are not correctly retained and assigned to the object instance in some cases.
Hopefully my changes are correct, I'm not super familiar with the code base so it would be helpful to have a second opinion. I can add extra test cases if needed, not sure what might be required, if anything.
- connect to #1547
- see also https://github.com/strongloop/loopback-datasource-juggler/pull/1542
> Fix datasource not correctly retaining name value

- lib/datasource.js
A clean up of https://github.com/strongloop/loopback-datasource-juggler/pull/1554
> Use more meaningful names for dataSource and connector

- lib/datasource.js
- test/datasource.test.js
This is a follow-up to https://github.com/strongloop/loopback-datasource-juggler/pull/1555
> fix: add more tests to verify new DataSource()

- lib/datasource.js
- test/datasource.test.js
One more edge case to keep it backward compatible.
> fix: allow `new DataSource(connector, settings)`

- lib/relation-definition.js
- test/relations.test.js
Related to https://github.com/strongloop/loopback/issues/2882
- `Person` EmbeddsMany `Address`
- create a new person `let p = new Person({name: 'Jack', id: 1})`
The generated instance is `{name: 'Jack', id: 1, addresses: []}`
In this PR I add a flag `omitDefaultEmbeddedItem`
Same as current behaviour, the new person instance have an empty array property `addresses` 
The new person instance is `{name: 'Jack', id: 1}`
Please note it doesn't have the embedded item.
> feat: omit default fn for embedsMany

- lib/datasource.js
- lib/model-builder.js
- test/datasource.test.js
Add API allowing consumers (e.g. LoopBack) to remove a Model from all
juggler registries:
- ModelBuilder's models
- ModelBuilder's definitions
- Connector registry of models
- connect to strongloop/strong-remoting#444
> feat: remove a Model from all registries

- lib/utils.js
When running `npm test` of `loopback` locally, I noticed a test failure when running on PhantomJS browser:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0) app 
"before each" hook for "can be read via `app.get(key)`" FAILED
undefined is not a constructor (evaluating 'Number.isFinite(rank)')
```
This change is fixing the problem by adding a polyfill for `Number.isFinite()` function. The API was introduced as part of ES6/ES2015 spec and is not supported by PhantomJS.
- n/a
> Polyfill Number.isFinite() to support PhantomJS

- .gitignore
- .npmignore
- index.d.ts
- lib/datasource.js
- package.json
- tsconfig.json
- types/common.d.ts
- types/connector.d.ts
- types/datasource.d.ts
- types/inclusion-mixin.d.ts
- types/kv-model.d.ts
- types/model.d.ts
- types/observer-mixin.d.ts
- types/persisted-model.d.ts
- types/query.d.ts
- types/relation-mixin.d.ts
- types/relation.d.ts
- types/scope.d.ts
- types/transaction-mixin.d.ts
- types/validation-mixin.d.ts
This PR adds basic TypeScript declarations for juggler related types to be referenced in LoopBack 4.
> Add TypeScript declaration files

- .travis.yml
- package.json
- test/loopback-dl.test.js
This builts on top of and supersedes #1545, please read the discussion there to learn more about the problems of the test that I am modifying in this pull request.
- Support for Node.js 8.x and 10.x is added because it's pretty much for free and people are already using LB 2.x on those versions
- Support for Node.js 4.x is dropped because it's no longer supported by the Node.js project.
cc @billinghamj  @joe-at-startupmedia 
#
> Add support for Node.js 8.x and 10.x, drop 4.x [2.x]

- lib/datasource.js
- test/datasource.test.js
- types/datasource.d.ts
Use case:
1. Configure a datasource with lazyConnect = true
2. Do NOT start the DB
3. Start the app
4. Send first request and it fails to connnect to the DB
5. Start the DB
5. Requests are now served correctly
- connect to https://github.com/strongloop/loopback-connector-mongodb/issues/268
> Fix datasource state management

- lib/dao.js
- lib/list.js
- test/basic-querying.test.js
- test/relations.test.js
- test/validations.test.js
Fix code and tests to be compatible with `should@10.x` which checks prototypes for comparison.
The extra step exposes some issues in our code:
- Invalid value for `regexp` operator error is not thrown correctly
- List (extends from Array) cannot be compared against plain array
- Validation errors 
> Fix tests to ensure upward compatibility w/ should@10

- .github/stale.yml
Prevent stalebot from auto-closing issues labelled as [good first issue
](https://github.com/strongloop/loopback-datasource-juggler/labels/good%20first%20issue). These issues are task for people who would like to start contributing to juggler, they should not be closed regardless of how long they have been opened.
> Fix stalebot config to ignore "good first issue"

- lib/dao.js
- test/persistence-hooks.suite.js
Before this change, many Operation Hooks were not correctly propagating changes made to `ctx.data` via reassigning ctx.data to a new object.
This change modifies existing tests to account for this different scenario, adds few more tests for scenarios that were not covered by tests before and finally fixes the problem discovered.
This pull request supersedes #1587.
/cc @juliendossantos 
> Fix Operation Hooks to propagate data changes

- types/common.d.ts
- types/model.d.ts
- types/persisted-model.d.ts
- Callback's first argument is an optional Error now. Was: required `any`.
- PersistedModel methods return `PersistedModel` now. Before this change, methods were returning `PersistedData` (`PersistedModel | AnyObject`). The problem with `AnyObject` is that it does not contain any `PersistedModel` instance data and cannot be assigned to functions expecting `Partial<PersistedModel>`. As a result, consumers of this API were forced to either cast the result to `PersistedModel` (which feels wrong) or deal with the `AnyObject` case (which never happen at runtime).
- Fix definition of `ModelData<T>` to `T | Partial<T>`. Before this change, `ModelData` allowed any values not related to the actual model at all, for example arrays.
These problems were discovered while working on …
> Fix type definitions for PersistedModel API

- lib/dao.js
- test/persistence-hooks.suite.js
add check before overriding context.data - fix the regression introduced by #1598
Co-Authored-By: Kyusung Shim <kyu.shim@ibm.com>
> Fix regression in Operation Hooks

- test/manipulation.test.js
When fixing https://github.com/strongloop/loopback-connector-cassandra/issues/65 by loading data from db after update, this test still failed because of assertation. What is got from db is `content: null`, while the asseration is `undefined`. This change can make the tests more robust.
- connect to https://github.com/strongloop/loopback-connector-cassandra/issues/65
> Fix "manipulation" tests to correctly handle databases returning null instead of undefined

- types/datasource.d.ts
This PR adds EventEmitter method type information to DataSource.
This is so that the TS compiler does not complain if we try to attach a listener to the datasource
strongloop/loopback-next#1553
> Add EventEmitter type information to DataSource type

- lib/relation-definition.js
- test/relations.test.js
**Backport of #1532**
_In general, we don't backport new features to LTS versions because of stability reasons. Having said that, this particular change looks more like a bug fix to me, thus I think it's ok to add it to 2.x version too._
Related to https://github.com/strongloop/loopback/issues/2882
- `Person` EmbeddsMany `Address`
- create a new person `let p = new Person({name: 'Jack', id: 1})`
The generated instance is `{name: 'Jack', id: 1, addresses: []}`
In this PR I add a flag `omitDefaultEmbeddedItem`
Same as current behaviour, the new person instance have an empty array property `addresses` 
The new person instance is `{name: 'Jack', id: 1}`
Please note it doesn't have the embedded item.
> feat: omit default fn for embeds many (2.x)

- lib/dao.js
- test/manipulation.test.js
- test/model-inheritance.test.js
Fix for #1422 
---
Update:
It should also fix issue https://github.com/strongloop/loopback-connector-mongodb/issues/445
> fix: alllow updates with unknown properties if strict=filter

- lib/utils.js
- package.json
- test/async-observer.test.js
- test/kvao/_helpers.js
- test/kvao/expire.suite.js
- test/kvao/get-set.suite.js
- test/kvao/iterate-keys.suite.js
- test/kvao/keys.suite.js
- test/kvao/ttl.suite.js
- test/operation-hooks.suite/embeds-many-destroy.suite.js
- test/operation-hooks.suite/embeds-many-update-by-id.suite.js
If we want to start writing `async` functions using `await` statements then we must remove Bluebird from our public API. This pull request is doing exactly that.
This is a breaking change. Juggler methods are no longer returning instances of Bluebird Promise, but return a native Promise instead.
As a result, API consumers can no longer use sugar APIs provided by Bluebird, e.g. `spread`, `delay`, etc.
Migration guide: rewrite your code from `.then()` style into `async` functions using `await` statements.
> [SEMVER-MAJOR] Switch from Bluebird to native Promise

- README.md
Back-port #1633 to 2.x version line, see https://github.com/strongloop/loopback-next/issues/1744
> Describe LTS versions in README [2.x]

- README.md
Back-port #1633 to 3.x version line, see https://github.com/strongloop/loopback-next/issues/1744
> Update LTS versions in README [3.x]

- lib/dao.js
- test/crud-with-options.test.js
Moved `removeUndefined` call to the proper location. This way when sending partial document updates in embedded documents, rest properties do not get converted to null in MongoDB
- connect to #1622 
> Fix patchAttributes for embedded document properties in MongoDB

- lib/dao.js
- test/crud-with-options.test.js
Calling patchAttributes without all embedded properties inits to null.
This is a back-port of https://github.com/strongloop/loopback-datasource-juggler/pull/1623
cc @mitsos1os
> remove null in embedded doc properties updates [3.x]

- lib/relation-definition.js
- lib/utils.js
- test/util.test.js
Saving (very) large objects with loopback can result in node spinning for a long time (>50s in my case) on a single statement checking the uniquness of a list of IDs of child objects.  This causes lots of issues, including connection timeouts, and service heartbeat / health-check failures.
The implementation of this uniquenss check is currently a naieve and extremely inefficient O(N^2) one, which can be trivially accelerated for common ID datatypes.
N/A
> fix: accelerate unique id checking

- lib/include.js
- lib/include_utils.js
- test/include.test.js
- test/include_util.test.js
https://github.com/strongloop/loopback/issues/4028
> Report errors for missing id properties for include

- lib/dao.js
- lib/include.js
- lib/include_utils.js
- lib/utils.js
- test/allow-extended-operators.test.js
- test/model-definition.test.js
- test/util.test.js
If we allow hidden properties to be part of the query condition, there is security risk for brute-force guessing.
It also checks circular and deep objects to avoid DoS attack.
> Report errors if where clause contains hidden properties

- lib/dao.js
- lib/model.js
- test/model-definition.test.js
Model settings hidden/protected properties can be an array or object, such as:
- hidden: ['secret']
- hidden: {secret: true}
#1646 
> Allow hidden/protected props as an object

- lib/dao.js
- lib/include.js
- lib/utils.js
- test/loopback-dl.test.js
- test/model-definition.test.js
- Fixes #1645
- Do not apply hidden property check for data. Only report issues with query.
- Fixes #1648
- Allow prohibitHiddenPropertiesInQuery to be configured in model/datasource settings.
> Improve hidden/protected property checks

- docs.json
Add in some missing files from our `lib` directory, so their JSDocs show up at https://apidocs.strongloop.com/loopback-datasource-juggler.
Question: should we include files under `lib/connectors` and `lib/kvao`?
> chore: update file list for apidocs

- lib/dao.js
- test/model-definition.test.js
This PR allows certain settings to be passed via method level `options` in addition to `model` and `datasource` level settings.
This ability makes it possible to use `createOptionsFromRemotingContext` to force certain policies if the request is remote.
See https://github.com/strongloop/loopback-datasource-juggler/pull/1638#issuecomment-437407868
> Allow flags to be passed via options

- lib/connectors/memory.js
- lib/dao.js
- lib/include.js
- lib/model-utils.js
- lib/model.js
- lib/utils.js
- test/model-definition.test.js
- test/util.test.js
This PR uses `options` from remote requests to decide default values for certain security-related settings
See https://github.com/strongloop/loopback-datasource-juggler/pull/1638#issuecomment-437407868
https://github.com/strongloop/loopback-datasource-juggler/issues/1663
> Use options.remotingContext for conditional settings

- .eslintrc
- lib/datasource.js
- test/datasource.test.js
- types/datasource.d.ts
Implement a new helper API for calling connector's "execute" method
in a promise-friendly way.
Example usage:
```ts
await MyModel.dataSource.execute(
'SELECT * FROM Users WHERE email = ?',
['alice@example.com'],
{/* options */});
```
While it's possible to call `MyModel.dataSource.execute` directly, this new API adds promise support to existing callback-based connectors. When we upgrade connector API to use promises under the hood, consumers of this new API won't be affected by that change, as opposed to consumers of `connector.execute` that will have to upgrade their code.
/cc @koalabi 
- connect to strongloop/loopback-next#2053
- StackOverflow: [How to execute arbitrary SQL query](https://stackoverflow.com/q/53338050/69868)
> feat: dataSource.execute(cmd, args, opts, cb)

- test/include.test.js
Fix include test which was using an unknown property name in `fields` object so downstream PRs and tests can pass. The `posts` property doesn't exist on `User` model, so use `name` instead.
> fix: use existing field in exclude test

- types/model.d.ts
- Define two new types: ModelSettings and ModelProperties to describe the objects describing model properties and settings.
- Add static property `base` and static method `extend` to the definition
of `ModelBase` class.
- Add property `defaultModelBaseClass` to `ModelBuilder` class definition.
- Fix `PropertyDefinition` interface: remove `name`, add optional `id`.
These issues were discovered while working on https://github.com/strongloop/loopback-next/pull/2274.
> Improve Model type definitions

- types/connector.d.ts
- types/persisted-model.d.ts
Fix return type of PersistedModel's `findOrCreate` function so that it conforms to the return contract of connectors which support it (took mongodb and memory as examples). Also, add a string index signature to the `Connector` interface to allow checks for atomic functions.
Connect to https://github.com/strongloop/loopback-next/issues/1956. 
> fix: update typescript declarations

- lib/dao.js
- test/basic-querying.test.js
When using [near](https://loopback.io/doc/en/lb2/Where-filter.html#near) operator in a filter for find operations, The code path taken for memory connector is different than other connectors which support this feature. 
For memory connector, the call stack is as follows: DAO.find() -> invokeConnectorMethod() with the callback provided as `allCb` -> (after connector's all/find method returns) allCb() does some processing (converting model PDO (plain data object) to model instance) and calls utils.createPromiseCallback(). 
For MySQL/MongoDB, the call stack is: DAO.find() -> invokeConnectorMethod() with `geoCallBack` being the cb function -> eventually geoCallBackWithoutNotify() is called which creates a model instance with a memory connector and calls `memory.all()` but this time supplies …
> Fix callback for find queries with near filters

- lib/model-builder.js
- test/datatype.test.js
Currently, a model definition like this:
```
"properties": {
"items": {
"type" : {
"itemname": { "type": "string"},
"type": { "type": "string" }
}
}
}
```
results in invalid data.
`{ items: [object Object] }`
It is caused by the sub-property `type` conflicting with the type resolution object.
This PR, allows sub-property `type` to be used without any problem.
https://github.com/strongloop/loopback/issues/4131
> feat: Support "type" key in sub-properties

- lib/model-builder.js
- test/datatype.test.js
Currently, a model definition like this:
```
"properties": {
"items": {
"type" : {
"itemname": { "type": "string"},
"type": { "type": "string" }
}
}
}
```
results in invalid data.
`{ items: [object Object] }`
It is caused by the sub-property `type` conflicting with the type resolution object.
This PR, allows sub-property `type` to be used without any problem.
https://github.com/strongloop/loopback/issues/4131
> feat: Support "type" key in sub-properties in 3.x

- lib/model-builder.js
- test/datatype.test.js
Currently, a model definition like this:
```
"properties": {
"items": {
"type" : {
"itemname": { "type": "string"},
"type": { "type": "string" }
}
}
}
```
results in invalid data.
`{ items: [object Object] }`
It is caused by the sub-property `type` conflicting with the type resolution object.
This PR, allows sub-property `type` to be used without any problem.
https://github.com/strongloop/loopback/issues/4131
> feat: Support "type" key in sub-properties in 2.x

- lib/list.js
- test/introspection.test.js
POST request body:
```
{ items": [
[
{"name": "APPLE"},
{"serial": 67}
]
]
}
```
Currently stored as: 
```
{ "items": [
{
"0": {
"name": "APPLE"
},
"1": {
"serial": 67
}
}
]
}
```
Will be stored as:
```
{ items": [
[
{
"name": "APPLE"
},
{
"serial": 67
}
]
]}
```
https://github.com/strongloop/loopback/issues/4132
> feat: support array within array

- lib/list.js
- test/introspection.test.js
POST request body:
```
{ items": [
[
{"name": "APPLE"},
{"serial": 67}
]
]
}
```
Currently stored as: 
```
{ "items": [
{
"0": {
"name": "APPLE"
},
"1": {
"serial": 67
}
}
]
}
```
Will be stored as:
```
{ items": [
[
{
"name": "APPLE"
},
{
"serial": 67
}
]
]}
```
https://github.com/strongloop/loopback/issues/4132
> feat: support array within array in 3.x

- lib/dao.js
- test/basic-querying.test.js
- test/defaults.test.js
- test/manipulation.test.js
Before this change, when a property was configured with a default value at LoopBack side and the database was returned a record with a missing value for such property, then we would supply use the configured default.
This behavior is problematic for reasons explained in #1692.
~~In this commit, we are introducing a new model-level setting called `applyDefaultsOnReads`, which is enabled by default for backwards compatibility.~~
~~When this setting is set to `false`, operations like `find` and `findOrCreate` will NOT apply default property values on data returned by the database (connector).~~
In this pull request, we are fixing DAO operations like `find` and `findOrCreate` so that they do NOT apply default property values on data returned by the database (connector).
Please note that most …
> fix: do not apply default values on data from database

- test/basic-querying.test.js
- test/manipulation.test.js
In #1705, I had to modify the tests added by #1704 to make them pass on different databases (SQL vs NoSQL, etc.)
This pull request is cherry-picking the changes from #1705 into master.
-  #1704, #1705 and #1692
> Improve tests for empty vs. default values

- lib/dao.js
- test/basic-querying.test.js
- test/manipulation.test.js
Before this change, when a property was configured with a default value at LoopBack side and the database was returned a record with a missing value for such property, then we would supply use the configured default.
This behavior is problematic for reasons explained in #1692.
In this commit, we are introducing a new model-level setting called `applyDefaultsOnReads`, which is enabled by default for backwards compatibility.
When this setting is set to `false`, operations like `find` and `findOrCreate` will NOT apply default property values on data returned by the database (connector).
Please note that most of the other CRUD methods did not apply default values on database data as long as the connector provided native implementation of the operation, that aspect is not changing.
Also note …
> Do not apply default values on data from database [2.x]

- package.json
CI for `loopback-datasource-juggler` is failing because one of the downstream `loopback-connector-kv-extreme-scale` failed.  
From @bajtos, we used to have an instance for testing but not anymore.  Since `loopback-connector-kv-extreme-scale` has low usage, we have decided to:
- have https://github.com/strongloop/loopback-connector-kv-extreme-scale/issues/23 to keep track of the CI failure
- remove this from downstream of juggler, so that we can get the more important PRs to land first. 
Related to: https://github.com/strongloop/loopback-datasource-juggler/pull/1705#issuecomment-480254509
> Remove kv-extreme-scale connector from downstream test

- lib/include.js
- test/include.test.js
- On `{include: true}` or `{include: 1}` the lib crashes with
"TypeError: includes.forEach is not a function".
- Fix by checking for boolean and number type and return empty array.
- connect to #1580 {include: true} or {include: 1} throws TypeError
> fix: normalize include with boolean or number

- lib/include.js
- test/include.test.js
Back-port #1581 to 2.x. The first commit was cherry-picked from 4.x by git, the second commit makes changes necessary to pass the tests.
/cc @spurreiter
See also #1580
> fix: normalize include with boolean or number [2.x]

- lib/dao.js
- lib/list.js
- test/basic-querying.test.js
- test/datatype.test.js
- test/manipulation.test.js
Ensure that nested array properties maintain connector-specific data type metadata and also coerce string values for array of primitive properties into their type. Connect to https://github.com/strongloop/loopback-connector-mongodb/issues/493.
> fix: nested property coercion and resolution

- test/include.test.js
A follow up PR for https://github.com/strongloop/loopback-connector-couchdb2/pull/59.
Fix the 2 tests mentioned in https://github.com/strongloop/loopback-connector-couchdb2/pull/59 by adding index to the `title` field.
> Fix: add index for couchdb

- .travis.yml
- lib/date-string.js
- lib/model-utils.js
- lib/model.js
- Fix code to pass all tests on Node.js 12
- Add Node.js 12 to the list of Travis CI platforms
> Add support for Node.js 12.x

- .travis.yml
- lib/date-string.js
- lib/model-utils.js
- lib/model.js
Back-port https://github.com/strongloop/loopback-datasource-juggler/pull/1728:
- Fix code to pass all tests on Node.js 12
- Add Node.js 12 to the list of Travis CI platforms
> Add support for Node.js 12.x [3.x]

- test/manipulation.test.js
~~Strangely enough, the changes made to `test/manipulation.test.js` by #1707 are not present in the current `master` branch. This pull request is (re)introducing them back again.~~
The changes made by #1707 were not fixing all new tests to pass on SQL. This patch applies the same changes on other tests and thus makes the shared test suite pass with SQL connectors.
See also #1692
> Fix tests for empty vs. default values to pass on SQL

- lib/dao.js
- lib/model-utils.js
- test/manipulation.test.js
- test/model-utils.test.js
Fixes #1723. Make sure we coerce nested property values for DAO methods like `updateAll`.
> fix: allow coercion of nested properties [3.x]

- README.md
- package.json
- Update `README` on LTS status. Related to https://github.com/strongloop/loopback/issues/4180
- add `"author": "IBM Corp.",` in package.json so that `slt copyright` command can generate the right header.
There will be 109 files with copyright year changes, so I'll submit it in a separate PR for easier review.
> chore: update LTS status

- lib/datasource.js
- test/datasource.test.js
Fix DataSource constructor to create a shallow copy of the settings object provided by the caller. This prevents surprising behavio where changes made to `ds.settings` were picked up by the provided config object, as observed e.g. in tests of our MongoDB connector.
- https://github.com/strongloop-internal/scrum-apex/issues/416
> datasource: copy settings object in constructor

- lib/date-string.js
- test/date-string.test.js
Quoting from https://github.com/strongloop/loopback-datasource-juggler/pull/1591:
> The issue happens when using PersistedModel.upsert or PersistedModel.upsertWithWhere methods - that for some reason instance values twice - with model that uses DateString type
- resolves #1591
> Fix DateString constructor to accept DateString instances

- lib/dao.js
- test/memory.test.js
The first commit is reworking the setup of the Operation Hooks test suite for memory connector so that the "unoptimized" variant disables not only atomic CRUD operations, but also geo queries.
This way we can test both "near" querying implementations:
- When the connectors supports "near" queries natively.
- When "near" queries are executed at LoopBack side in-memory.
The second commit fixes "loaded" hook for unoptimized "near" queries (as demonstrated by a failing test).
The third commit fixes "access" hook for unoptimized "near" queries (as demonstrated by a failing test).
These changes are needed to make MongoDB connector tests pass when running against juggler v4.
- https://github.com/strongloop-internal/scrum-apex/issues/416
> Fix implementation of Operation Hooks for "near" (geo) queries

- lib/dao.js
- test/memory.test.js
The first commit is reworking the setup of the Operation Hooks test suite for memory connector so that the "unoptimized" variant disables not only atomic CRUD operations, but also geo queries.
This way we can test both "near" querying implementations:
- When the connectors supports "near" queries natively.
- When "near" queries are executed at LoopBack side in-memory.
The second commit fixes "access" hook for unoptimized "near" queries (as demonstrated by a failing test).
- this pull request is back-porting https://github.com/strongloop/loopback-datasource-juggler/pull/1739 to 3.x
> Fix implementation of Operation Hooks for "near" (geo) queries [3.x]

- lib/relation-definition.js
- test/relations.test.js
* Fix for #1724 - Added options to attribute updates
* Fix for #1724 - Added unit tests for options
PR for cherry picking back to 3.x branch.
> Fix for #1724 - Added options to attribute updates (#1725)

- lib/observer.js
- test/async-observer.test.js
The connector hook "after operation"  is not called in case of an error caused by the connector.
This for example does not allow to change the HTTP status code for specific errors. Instead HTTP 500 Internal Server Error is returned. 
This PR calls the "after operation" even in such situations. The original error is passed with `ctx.res.err` to allow inspection and manipulation as described in https://loopback.io/doc/en/lb3/Connector-hooks.html#error-handling.
> feat: call after operation hook in case of errors

- types/common.d.ts
In version 4.0.0, we switched from Bluebird to native Promises - see https://github.com/strongloop/loopback-datasource-juggler/pull/1631
I discovered the inconsistency between the implementation and the typings while experimenting with optimizing dependencies of `@loopback/repository` (loosely related to https://github.com/strongloop/loopback-next/issues/3126).
> Fix types to describe native Promise

- test/include.test.js
To unblock https://github.com/strongloop/loopback-connector-cloudant/pull/206.
We have the same fix in 3.x https://github.com/strongloop/loopback-datasource-juggler/blob/3.x/test/include.test.js#L1556
> test: add property index to support cloudant

- README.md
Since we've extended the EOL date for LB3 to be Dec 2020, we should change the EOL for this module for v3.x accordingly.
Related: strongloop-internal/scrum-loopback#1438
> update LTS in README

- types/persisted-model.d.ts
Connect to https://github.com/strongloop/loopback-next/issues/2614. We need to add `beginTransaction()` to the persisted model declaration file in order to utilize it with LB4 repositories.
> chore: add beginTransaction API to declaration file

- lib/datasource.js
- test/transaction.test.js
- types/datasource.d.ts
- types/persisted-model.d.ts
Enable `beginTransaction()` API for datasources to call Transaction's `begin()` method in `loopback-connector`. This returns a transaction instance that can be used independently by LB4's repositories.
- connect to https://github.com/strongloop/loopback-next/issues/2614
- blocked on https://github.com/strongloop/loopback-connector/pull/147
> Add `beginTransaction` method for datasources

- lib/datasource.js
- test/datasource.test.js
Defer automigrate/autoupdate until we are connected, so that connection errors can be reported back to callers.
Fix `postInit` handler to not report connection error to `console.log` and via dataSource "error" event in case there is already an operation queued. When this happens, we want the error to be handled by the queued operation and reported to its caller.
- fixes https://github.com/strongloop/loopback-next/issues/3044
> fix: report errors from automigrate/autoupdate

- lib/datasource.js
- test/datasource.test.js
- types/datasource.d.ts
When writing tests, for performance reasons we often want to reuse the same data-source instance for many tests suites. At the same time, we want to keep such test suites independent and allow them to reuse the same model name for different model classes.
Juggler does support redefinition of a model with the same name.
This change is adding a new API called `dataSource.reset()` that allows tests to remove all old models before creating new ones (typically from a `before` hook).
This is very loosely related to https://github.com/strongloop/loopback-next/pull/3387.
> feat: add DataSource.deleteAllModels() API

- types/datasource.d.ts
Related to https://github.com/strongloop/loopback-next/issues/2614 and https://github.com/strongloop/loopback-next/pull/3397.
> fix: use only promises for beginTransaction

- lib/datasource.js
The autoupdate method was queueing `automigrate`. This bug was introduced in 40286fcd28cc0119e8530d56ff0d82bc55f4517d.
- Fixes #1761
> Fix autoupdate queueing automigrate instead

- lib/dao.js
- test/manipulation.test.js
Before this change, when both the PK value (`id`) and the `data` object were provided as plain-data values (e.g. as received in a JSON request), and the connector was using a complex PK type (e.g. `ObjectID` in MongoDB), then `replaceById` operation was printing confusing warnings:
WARNING: id property cannot be changed from 5d39775a59f5f541513c5e05
to 5d39775a59f5f541513c5e05 for model:Post
in 'before save' operation hook
WARNING: id property cannot be changed from 5d39775a59f5f541513c5e05
to 5d39775a59f5f541513c5e05 for model:Post
in 'loaded' operation hook
This commit fixes the problem by applying the same type coercion on the PK value (`id`) as has been applied by the model constructor on the PK property (`data.id`).
I discovered this problem while working on the spike for Inclusion …
> Fix coercion of PK value in `replaceById` method

- lib/datasource.js
- test/datasource.test.js
If establishing a database connection is slow and database migration runs and there are many models, sql operations are queued up and this leads to the node.js max emitters exceeded warning.
A default value for max emitters has now been introduced, and it can also be configured in datasources.json.
- connect to https://github.com/strongloop/loopback-next/issues/2198
> fix: prevent max listeners warning

- .travis.yml
- package.json
> drop support for Node.js 6

- lib/dao.js
- test/defaults.test.js
Adds the ability to ignore writing default values to the database in `4.x`. Port of https://github.com/strongloop/loopback-datasource-juggler/pull/1770 (`3.x`).
> feat: add applyDefaultOnWrites property

- lib/dao.js
- test/defaults.test.js
Adds the ability to ignore writing default values to the database.
- connect to https://github.com/strongloop/loopback-connector-mongodb/issues/534
> feat: add applyDefaultOnWrites property [3.x]

- test/basic-querying.test.js
- test/datatype.test.js
Existing identifier length exceeds Oracle DB's limit.
https://github.com/strongloop/loopback-connector-oracle/issues/183
> chore: reduce identifier length [4.x]

- test/basic-querying.test.js
- test/datatype.test.js
Existing identifier length exceeds Oracle DB's limit.
https://github.com/strongloop/loopback-connector-oracle/issues/183
> chore: reduce identifier length [3.x]

- lib/utils.js
- test/basic-querying.test.js
- test/memory.test.js
- test/util.test.js
Fix the case where an invalid RegExp string is queried on a model. Instead of crashing the app,
we first check if the query can be successfully converted to RegExp and if not, it is sanitized.
Fixes #1781 
> Make sure invalid RegExp string is properly sanitized in query

- lib/utils.js
- test/basic-querying.test.js
- test/memory.test.js
- test/util.test.js
> backport #1782 to 3.x

- package.json
We don't have any IBMi instances suitable for running CI builds for this connector.
See also https://github.com/strongloop/loopback-connector/pull/159
> chore: remove loopback-connector-ibmi from downstream list

- lib/model.js
- test/defaults.test.js
Adds support for `applyDefaultOnWrites` in nested properties. Addressed https://github.com/strongloop/loopback-connector-mongodb/issues/552.
> feat: support applyDefaultOnWrites in nested properties

- lib/dao.js
- test/manipulation.test.js
Model Creation wiht `create` and replacement with `replaceById`, when error in model initialization they now properly return the rejected promise instead of leaving it unhandled and missing the return value.
Fixes #1789 
> Convert error from a property setter to a rejected promise

- package.json
`async@3.0.0` release notes: https://github.com/caolan/async/blob/master/CHANGELOG.md#v300
AFAICT, the only breaking change introduced by `strong-globalize@5.0.0` is requiring Node.js 8.9 or newer.
> Update strong-globalize and async to their latest versions

- types/datasource.d.ts
Remove usage of `PromiseOrVoid`, it makes it difficult to consume the API via `await`. For each async method, define multiple variants to correctly describe what's returned when a callback arg was provided (`void`) and what's returned when called with no callback (`Promise<T>`).
See https://github.com/strongloop/loopback-next/pull/4235 for background information.
> Fix Promise/Callback variants in datasource types

- lib/list.js
- test/list.test.js
- You can do new Array(4) to generate an array with 4 empty items
- Doing the same with list caused an error
- This broke lodash.deepclone
- This PR restores compatibility with the array constructor
Fixes #1798
> Fix issue with broken compatibility with array constructor

- types/datasource.d.ts
Looks like I forgot to push the fix to #1807 before landing.
> Fix typo introduced by 19048cd7

- lib/dao.js
Investigate the failure on vm node 12 https://github.com/strongloop/loopback-datasource-juggler/pull/1805
There are 3 failures on Node.js 12, this PR fixes the first two. 
The third one will be fixed in anther PR.
Error report see [link](https://cis-jenkins.swg-devops.com/job/nb/job/loopback-datasource-juggler~2.x/label=x64%20&&%20linux%20&&%20nvm,nodeVersion=12/21/console)
Copy it here:
```
3 failing
14:32:14 
14:32:14   1) DataAccessObject coerces where clause with array-like objects {"and":{"0":{"age":"10"},"1":{"vip":"true"}}}:
14:32:14 
14:32:14       AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:
14:32:14 
14:32:14 {
14:32:14   and: {
14:32:14     '0': {
14:32:14       age: 10
14:32:14     },
14:32:14     '1': {
14:32:14       vip: true
14:32:14     } …
```
> Fix model coerce

- lib/dao.js
- lib/model.js
- lib/utils.js
- test/default-scope.test.js
Without this protection, incoming objects from the network can overwrite
the ModelConstructor prototype.
> fix(security): avoid prototype pollution on model create and update

- lib/model.js
- test/defaults.test.js
Ignores value if it matches default value.
**Use case**: User wants to reduce noise in the database, since the defaults will be filled in by LoopBack or the front-end framework. Makes a big difference if there are thousands of such properties in millions of records.
> feat: added persistDefaultValues

- docs/definition-language.md
- lib/datasource.js
Fixes https://github.com/strongloop/loopback-next/issues/4042
> fix: warn about strict cannot be false with relational dbs

- lib/datasource.js
- package.json
- test/discovery.test.js
Connects to https://github.com/strongloop/loopback-next/issues/3343
Allows users to keep the property name as the same as the db columns names. It can be set by `options.useDefaultCase` to false.
To close #3343, we need to:
1. modify Juggler (this PR)
2. update LB3 docs ( https://github.com/strongloop/loopback.io/pull/928)
3. update `lb4 discover` CLI and docs ( need this PR to be landed first)
> feat: allows different naming conventions for db  columns for discover

- types/observer-mixin.d.ts
Added typings for supporting operation hooks in LB4. Part of addressing https://github.com/strongloop/loopback-next/issues/3952.
Signed-off-by: Hage Yaapa <hage.yaapa@in.ibm.com>
> feat: add OperationHookContext interface

- types/observer-mixin.d.ts
The changes introduced by dcfda58 (#1820) may break existing consumers of our typings. This commit fixes this problem by adding a default value to the recently introduced generic argument of `Listener` type.
> Add default generic arg value to `Listener` type

- .eslintignore
- .npmignore
- types/__test__.ts
- types/model.d.ts
- types/observer-mixin.d.ts
See https://github.com/strongloop/loopback-datasource-juggler/pull/1820 and https://github.com/strongloop/loopback-next/pull/4730.
> Add ObserverMixin to ModelBase typings

- types/observer-mixin.d.ts
Improved Listener signature so it can accept callback or promise.
Addresses https://github.com/strongloop/loopback-next/pull/4730/files#r385912758, required for landing PR https://github.com/strongloop/loopback-next/pull/4730/.
The `observe` and `removeObserver` methods of a class implementing `ObserverMixin` can accept a callback or a promise. The current typing does not allow that. This PR re-defines the `Listener` type to be either a callback that returns `void` or a promise that resolves to `void`. 
The problem this PR solves manifests only in TS projects, like LB next, hence it cannot be tested in the Juggler repository.
Before settling on this change, we tried another approach:
```ts
export interface Listener<Ctx = OperationHookContext<typeof ModelBase>> {
(ctx: Ctx, next: (err?: …
```
> chore: improve Listener signature

- lib/list.js
Move wrong re-initialization of `List.prototype.toItem` on every instatiation, to proper prototype usage.
This was separated from #1787 by @bajtos  to be landed separately and backported
See also #1787 
> Move List.prototype.toItem out of inner init

- .mocharc.yaml
- package.json
- test/mocha.opts
- Update mocha to 7.x and nyc to 15.x.
- Add mocharc, remove mocha.opts. Mocha has deprecated `mocha.opts` in favour of RC files. See also https://mochajs.org/#configuring-mocha-nodejs
> Update dev dependencies + rework Mocha config

- lib/list.js
- lib/model-builder.js
- lib/model.js
- lib/utils.js
- test/basic-querying.test.js
- test/helpers/setup-parent-ref.js
- test/list.test.js
- test/model-builder.test.js
_This pull request supersedes #1787 by @mitsos1os. I cleaned up the commit history and also tweaked code formatting (white space) in few places._
Add a new hidden property `__parent` that's automatically set on all instances of embedded models.
For backwards compatibility, this feature is not enabled by default. You can turn it on by adding the following line to `server/server.js` file:
```js
app.registry.modelBuilder.settings.parentRef = true;
```
Resolve #1787 
> Add __parent reference to embedded models

- lib/datasource.js
- test/datasource.test.js
- types/datasource.d.ts
Implement `stop` as an alias for `disconnect`. This way LB4 applications don't have to include custom `stop` implementation in every datasource file.
Intended datasource file:
```ts
@lifeCycleObserver('datasource')
export class DbDataSource extends juggler.DataSource
implements LifeCycleObserver {
static dataSourceName = 'db';
constructor(
@inject('datasources.config.db', {optional: true})
dsConfig: object = config,
) {
super(dsConfig);
}
}
```
Compare with the current template:
```ts
@lifeCycleObserver('datasource')
export class DbDataSource extends juggler.DataSource
implements LifeCycleObserver {
static dataSourceName = 'db';
constructor(
@inject('datasources.config.db', {optional: true})
dsConfig: object = config,
) {
super(dsConfig);
}
/**
* Start the datasource when application is …
```
> feat: implement DataSource.stop()

- types/datasource.d.ts
This is a follow-up for https://github.com/strongloop/loopback-datasource-juggler/pull/1835.
Change the return value of `DataSource.stop()` from `Promise<void>` to `void | PromiseLike<void>` to avoid breaking existing LoopBack 4 applications, where DataSource subclasses are scaffolded with `stop(): ValueOrPromise<void>`.
Before the change, build of loopback-next was failing with the following errors (see https://github.com/strongloop/loopback-next/pull/5261)
https://travis-ci.com/github/strongloop/loopback-next/jobs/323793285
```
> loopback-next@0.1.0 build /home/travis/build/strongloop/loopback-next
> node packages/build/bin/compile-package -b
examples/multi-tenancy/src/datasources/db.datasource.ts:40:3 - error TS2416: Property 'stop' in type 'DbDataSource' is not assignable to the same …
```
> types: make DataSource.stop compatible with LB4

- types/datasource.d.ts
Fix type definitions to allow zero-argument invocation of the following database migration methods:
- `DataSource.automigrate()`
- `DataSource.autoupdate()`
Implementation-wise, when no model names are specified, then ALL models attached to the datasource are migrated.
> types: allow no `models` argument for automigrate

- types/__test__.ts
- types/datasource.d.ts
Add new overloads for `DataSource.execute` method to support non-SQL connectors like MongoDB.
See https://github.com/strongloop/loopback-next/issues/3342 for background and https://loopback.io/doc/en/lb3/Executing-native-SQL.html for the existing documentation for `db.execute` API.
> types: support non-SQL styles of `ds.execute`

- lib/datasource.js
- test/datasource.test.js
Add support for the following variants:
- `execute(collection, command, ...params, options)` (MongoDB)
- `execute(...params)` (forward-compatibility & other databases)
This is a follow-up for #1855, which added type descriptions for `execute` variants that turned out to be rejected by the actual (runtime) implementation. See also https://github.com/strongloop/loopback-next/issues/3342
The changes is pushing the responsibility for processing optional arguments (`(cmd)`, `(cmd, args)`, `(cmd, args, options)`) to the connector. This should be fine because the base `SqlConnector` already handles optional arguments (see [lib/sql.js#L551-L563](https://github.com/strongloop/loopback-connector/blob/bce6fa8c1f498340a5185dcd21545972a3cce7a7/lib/sql.js#L551-L563)), and we weren't really supporting …
> feat: improve `dataSource.execute` to support more flavors

- README.md
Add the Contributing section to README using https://github.com/strongloop/loopback.io#contributing as the reference.
Signed-off-by: Diana Lau <dhmlau@ca.ibm.com>
> chore: add contributing section to readme

- .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: Diana Lau <dhmlau@ca.ibm.com>
Update PR template to include DCO. Before, it's asking to read and sign CLA. 
> update PR template to include DCO

- test/manipulation.test.js
See https://github.com/strongloop/loopback-connector-mongodb/pull/563
> add tests for atomic upsertWithWhere

- lib/connectors/memory.js
- test/memory.test.js
Fix issues discovered by https://github.com/strongloop/loopback-next/pull/6676
- The where statement can be something like {toString: 'not a function'}
- Avoid object string comparison
Signed-off-by: Raymond Feng <enjoyjava@gmail.com>
> Fix value equality test to avoid toString

- test/manipulation.test.js
Introduce the new property atomicUpsertWithWhere for
connector that implement specific method.
See https://github.com/strongloop/loopback-connector-mongodb/pull/563
for mongodb implementation.
Backport #1864 
Signed-off-by: Matteo Padovano <mrbatista@users.noreply.github.com>
> chore: add test for atomic upsertWithWhere (#1864)

- .github/workflows/ci.yaml
> ci: restrict GITHUB_TOKEN permissions

- index.d.ts
- types/__tests__/date-string.spec.ts
- types/__tests__/geopoint.spec.ts
- types/__tests__/types.spec.ts
- types/date-string.d.ts
- types/geo.d.ts
- types/types.d.ts
Added typdef for:
- Any
- JSON
- Text
- GeoPoint
- DateString
Also see: https://github.com/microsoft/TypeScript/issues/22865#issuecomment-725015710
> feat: add built-in model property types typdef

- .github/workflows/ci.yaml
- .travis.yml
> ci: enable Node.js v17 testing

- lib/connectors/memory.js
- lib/dao.js
- package.json
- test/basic-querying.test.js
- test/common_test.js
- test/crud-with-options.test.js
- test/helpers/context-test-helpers.js
- test/persistence-hooks.suite.js
- types/persisted-model.d.ts
Signed-off-by: Samarpan Bhattacharya <this.is.samy@gmail.com>
Adds new createAll method to support insert multiple rows in single query in memory connector
Enables multiInsertSupport in memory connector
Adds capability to createAll in dao.js for models to do multiple insert in one query via the supported connectors
Fixes https://github.com/loopbackio/loopback-connector/issues/227
See also https://github.com/loopbackio/loopback-next/issues/3357
> feat: add capability for insert multiple rows in single query

- lib/datasource.js
- test/discovery.test.js
Signed-off-by: Muhammad Aaqil <aaqilniz@yahoo.com>
This PR adds a missing property `generated` to the model. The issue is happening while using lb4 to discover models. Discovering a model that has a constraint of auto_increment set to true doesn't work correctly. The discovery fails to pick up the auto_increment constraint. This was happening due to the fact that `loopback-datasource-juggler` was not attaching the property to the model properties being passed to the discover generator. This PR fixes that and attaches `generated: true/false` to the model. And sets `required` to `false` if a field has `generated` set to `true`.
Fixes #899
> fix: add missing property in model generated

- lib/dao.js
- test/common_test.js
- test/datatype.test.js
Signed-off-by: Samarpan Bhattacharya <this.is.samy@gmail.com>
The retuning model from createAll was not correct. It was not returning the serialized instance. Now rectified it and made it similar to create() function.
Fixes https://github.com/loopbackio/loopback-connector-postgresql/issues/530
> fix: return correct model instance in createAll

- lib/dao.js
- test/datatype.test.js
Signed-off-by: akshatdubeysf <akshat.dubey@sourcefuse.com>
Multiple calls to createAll were using a global context variable so this shared variable was causing unexpected behaviour for concurrent calls. Changed the scope of this variable to maintain a different instance for each call of createAll.
Fixes https://github.com/loopbackio/loopback-datasource-juggler/issues/2038
> fix: isolate context for each createAll call

- .github/workflows/ci.yaml
- package-lock.json
- package.json
BREAKING CHANGE: drop support for Node.js 14 version and lower
> chore: drop Node.js 14 and lower

- .github/workflows/ci.yaml
Currently, commit linter and code linter were broken because of the mismatch on the npm/node.js versions. I'm using the [github workflow file](https://github.com/loopbackio/loopback-next/blob/master/.github/workflows/continuous-integration.yml#L90-L91) in loopback-next as the reference. It seems like fixing the version of `actions/checkout` and `actions/setup-node` would fix the issue.
> fix(ci): fix GH actions versions

- .github/workflows/ci.yaml
- package.json
According to the [Node.js release schedule](https://nodejs.dev/en/about/releases/), Node.js 16 reached end of life on Sep 11, 2023.
> chore: drop Node.js 16 support

- lib/datasource.js
- test/discovery.test.js
Fixes #[9897](https://github.com/loopbackio/loopback-next/issues/9897)
> fix: set generated: false if the connector doesnot return it

- lib/datasource.js
In case of an unavailable datasource server (like the Redis server), the app crashes.
With this PR, the users can add an option in the datasource config named `catchFailure` and set its value to true. This would prevent the app from crashing and show the connection failure error in the console.
> fix: add error handling in case of unvailable cache server

- README.md
According to the LTS schedule for Node.js https://github.com/nodejs/Release, the EOL date for Node.js 20 is 2026-04-30. So we're updating the EOL date for this module accordingly.
> docs: update EOL date

- lib/datasource.js
> Fix discovering relations

- test/relations.test.js
loopback-connector-mongodb issue:  https://github.com/loopbackio/loopback-connector-mongodb/issues/776
> fix: unit test to support dynamic id key (_id vs id) in patient filter
